#!/bin/bash

meshes_2d="Triangles Quadrangles Cartesian Locally_Refined"
share=$TRUST_ROOT/Validation/Rapports_automatiques/Verification/PolyMAC/share/meshes

for mesh in $meshes_2d
do
    for n in "3"
    do
        mkdir -p $mesh/jdd_$n
        gunzip -c $share/$mesh/jdd_$n/mesh.med.gz >$mesh/mesh.med
        cp sep.data $mesh/cas.data
    done
done
