#!/bin/bash
[ ! -d cond_coup_fictif_vdf_impl ] && copie_cas_test cond_coup_fictif_vdf_impl || echo ""
[ ! -d cond_coup_fictif_vef_impl ] && copie_cas_test cond_coup_fictif_vef_impl || echo ""
[ ! -d cond_couple_vdf_impl ] && copie_cas_test cond_couple_vdf_impl || echo ""
[ ! -d cond_couple_vef_impl ] && copie_cas_test cond_couple_vef_impl || echo ""
