#!/bin/bash

cas=ICoCo_ChDonXYZ
if [ ! -f PAR_$cas.lml ]
then
   compare_lata $cas"_fields".lml $cas.lml 1>compare_lata.log 2>&1
else
   compare_lata PAR_$cas"_fields".lml PAR_$cas.lml 1>compare_lata.log 2>&1
fi
