#!/bin/bash
sed "s/tinit/nb_pas_dt_max 1 tinit/" conduc.data > petit.data 
echo "{ " > pb_mul.data
cat petit.data  | grep -v ^[fF]in | grep -v ^[eE]nd >> pb_mul.data
echo "}" >> pb_mul.data
cat petit.data >> pb_mul.data

trust pb_mul 2>  test.err 1> test.out
