#!/bin/bash
# rocALUTION : See https://github.com/ROCmSoftwarePlatform/rocALUTION

echo $TRUST_ROCALUTION
[ "$TRUST_ROCALUTION" = "" ] && exit

# On clone avant d'utiliser externalpackages dans le futur:
[ ! -d rocALUTION ] && git clone https://github.com/ROCmSoftwarePlatform/rocALUTION.git
cd rocALUTION
#git checkout eedff42d4badff # Contrat de progres CINES #
git checkout 985838b4e      # Pour beneficier de GlobalMatrix operationnel en sequentiel

# Build sans OpenMP et avec backend host si rocm pas installe:
SUPPORT_HIP=ON && [ "$ROCM_PATH" = "" ]        && SUPPORT_HIP=OFF && echo "Warning, ROCm non installe donc pas de support GPU."
SUPPORT_MPI=ON && [ "$TRUST_DISABLE_MPI" = 1 ] && SUPPORT_MPI=OFF
rm -r -f build
mkdir -p build
cd build
cmake .. -DSUPPORT_HIP=$SUPPORT_HIP -DROCM_PATH=$ROCM_PATH -DSUPPORT_OMP=OFF -DSUPPORT_MPI=$SUPPORT_MPI -DCMAKE_INSTALL_PREFIX=$TRUST_ROCALUTION || exit -1
# Bidouille pour ROCM anciens...
if [ -f $ROCM_PATH/include/rocsparse.h ]
then
   echo "Creating links for old Rocm version..."
   mkdir -p include/rocsparse && ln -s -f $ROCM_PATH/include/rocsparse.h include/rocsparse/rocsparse.h
   mkdir -p include/rocblas   && ln -s -f $ROCM_PATH/include/rocblas.h   include/rocblas/rocblas.h
fi
$TRUST_MAKE

# Install et copie des samples
make install || exit -1
cp -r clients $TRUST_ROCALUTION/clients

# Lancement du benchmark rocALUTION sur une petite matrice type de TRUST
cd $TRUST_ROCALUTION/clients/staging
gunzip -c $TRUST_ROOT/ThirdPart/src/LIBROCALUTION/VDF_10x10x10.mtx.gz > VDF_10x10x10.mtx
./benchmark VDF_10x10x10.mtx 2>&1 | tee benchmark.log
echo "`pwd`/benchmark.log created."

# Nettoyage
#rm -r -f $TRUST_ROOT/ThirdPart/src/LIBROCALUTION/rocALUTION

# Creation de l'include:
echo "#ifdef _COMPILE_AVEC_GCC_
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverloaded-virtual"
#include <rocalution.hpp>
#pragma GCC diagnostic pop
#else
#include <rocalution.hpp>
#endif
#ifdef ROCALUTION_ROCALUTION_HPP_
using namespace rocalution;
#endif" > $TRUST_ROCALUTION/include/rocalution_for_kernel.h

# Changement de la structure de rocALUTION:
cd $TRUST_ROCALUTION/include
if [ ! -f rocalution.hpp ]
then
   for item in rocalution/rocalution.hpp rocalution/version.hpp rocalution/base rocalution/solvers rocalution/utils
   do
      ln -s -f $item .
   done
fi
exit 0


