#!/bin/bash

# Generate SWIG of the TRUST ICoCo interface:

source $TRUST_MEDCOUPLING_ROOT/env.sh || echo "MEDCoupling not available"

if [[ ! -d "${MEDICoCo_project_directory}" ]] # variable not set
then
    cd $project_directory/share/swig
else # We are included in a sub project
    cd $MEDICoCo_project_directory/share/swig
fi

# Guess build mode from executable name.
BUILD_MODE=debug

if [ `echo $exec | grep _semi_opt$ 1>/dev/null 2>&1; echo $?` -eq 0  ]
then
   BUILD_MODE=semi_optim
elif [ `echo $exec | grep _opt$ 1>/dev/null 2>&1; echo $?` -eq 0  ]
then
   BUILD_MODE=optim
fi

make swig_$BUILD_MODE || exit 255
