#!/bin/bash

# Generate SWIG of the TRUST ICoCo interface:

source $TRUST_MEDCOUPLING_ROOT/env.sh || echo "MEDCoupling not available"
cd $project_directory/share/swig

mkdir -p build
rm -rf install

cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release
make -j install
