#!/bin/bash

# Generate SWIG of the TRUST ICoCo interface:

source $TRUST_MEDCOUPLING_ROOT/env.sh || echo "MEDCoupling not available"

if [[ -z ${MEDICoCo_project_directory} ]] # variable not set
then
    cd $project_directory/share/swig
else
    cd $MEDICoCo_project_directory/share/swig
fi

rm -rf install build
mkdir -p build

cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=$TRUST_ROOT/exec/python/bin/swig
make -j install
