#!/bin/bash

if [[ ! -d "${MEDICoCo_project_directory}" ]] # variable not set
then
    cd $project_directory/share/swig
else # we are included as a sub project
   cd $MEDICoCo_project_directory/share/swig
fi

./test_only.sh || exit 255

