include $(TRUST_ENV)/makefile

Lib = $(TRUST_LIB)/NOM_DE_LA_LIBRAIRIE

all : $(Lib).$(LIB_EXTENSION)
OBJS= \
	Base_modele.o \
	Champ_Inc_modele.o \
	Champ_modele.o \
	Equation_modele.o \
	Instanciable_modele.o \
	Interprete_modele.o \
	Modele_modele.o \
	Probleme_modele.o \
	Schema_Temps_modele.o \
	Source_modele.o \
	class_modele.o \
	cpp_modele.o \
	f_modele.o

$(Lib).a: $(OBJS)
	@ar cruv $(Lib).a *.o
	@echo "$(Lib).a est a jour"

$(Lib).$(SL_EXTENSION): $(OBJS)
	@echo "ca peut prendre un peu de temps ..."
	@$(CC) $(ShLibFlag) $(CppFlags) $(OBJS) -o $(Lib).$(SL_EXTENSION)
	@echo "$(Lib).$(SL_EXTENSION) est a jour"
SRCS= \
	Base_modele.cpp \
	Champ_Inc_modele.cpp \
	Champ_modele.cpp \
	Equation_modele.cpp \
	Instanciable_modele.cpp \
	Interprete_modele.cpp \
	Modele_modele.cpp \
	Probleme_modele.cpp \
	Schema_Temps_modele.cpp \
	Source_modele.cpp \
	class_modele.cpp \
	cpp_modele.cpp \
	f_modele.f

HDRS=

# DO NOT DELETE
