#!/bin/bash
# Check that Champ_fonc_reprise gives same result than classic restart: 
trust reprise_PolyMAC_P0.data 1>reprise_PolyMAC_P0.out_err 2>&1 || exit -1
compare_lata_gz Champ_fonc_reprise_PolyMAC_P0_bin.lml reprise_PolyMAC_P0.lml || exit -1
