#!/bin/bash
[ "$TRUST_USE_CUDA" != 1 ] && exit 0
echo "Testing AmgX solvers for implicit and pressure linear system..."
jdd=amgx
cp PETSC_AMGX.data $jdd.data
sed -i "1,$ s?solveur Petsc BICGSTAB?solveur amgx gmres?g" $jdd.data
sed -i "1,$ s?solveur_pression petsc cholesky { }?solveur_pression amgx gcp { precond c-amg { } seuil 1.e-12 impr }?g" $jdd.data
trust $jdd 1>$jdd.out_err 2>&1 || exit -1
gunzip -c PETSC_AMGX.lml.gz > ref.lml
compare_lata $jdd.lml ref.lml || exit -1
make_PAR.data $jdd
trust PAR_$jdd $? 1>PAR_$jdd.out_err 2>&1 || exit -1
compare_lata PAR_$jdd.lml ref.lml || exit -1
