#!/bin/bash
# Lancement lecture matrice generee
jdd=`pwd`
jdd=`basename $jdd`
matrix=`ls -rt Matrix_*.petsc | tail -1`
echo "Testing reading $matrix with petsc_matrix.sh..."
./petsc_matrix.sh $matrix 1>petsc_matrix.log 2>&1
exit $?
