#!/bin/bash
cas=`basename $1 .data`
echo $ECHO_OPTS "1,$ s?solveur_pression [Gg][Cc][Pp]?solveur_pression petsc gcp?g\nw Petsc_GCP_$cas.data" | ed $cas.data 1>/dev/null 2>&1
[ $? != 0 ] && exit -1
exit 0
