#!/bin/bash

source $TRUST_ROOT/Outils/lata2dx/lata2dx/install/env.sh
source $TRUST_ROOT/lib/src/LIBMEDCOUPLING/install/env.sh

python $TRUST_ROOT/Outils/lata2dx/lata2dx/Lata_to_med.py Obstacle.lata Obstacle.med
$MED_COUPLING_ROOT/bin/med2case Obstacle.med 
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Lata_to_case.py Obstacle.lata Obstacle2.case
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Lata_to_case.py -l Obstacle.lata Obstacle2_LastTS.case

visit -cli -s script_visit.py Obstacle.case nts_case1_all -nowin
visit -cli -s script_visit.py Obstacle2.case nts_case2_all -nowin
visit -cli -s script_visit.py Obstacle2_LastTS.case nts_case2_last -nowin

good="TRUE"

for i in {0..6}
do
    for field in VITESSE_SOM VITESSE_ELEM PRESSION_SOM PRESSION_ELEM
    do

	file1="Obstacle000"$i"."$field"_dom"
	file2="Obstacle2000"$i"."$field"_dom"

	diff -u $file1 $file2 > differences
	touch empty

	diff differences empty
	status=$?
	if [ $status -ne 0 ]
	then
	    echo "Error !! There are differences between files "$file1" and "$file2> my_text
	    good="FALSE"
	fi 
	rm -f empty
  
    done
done

if [ $good == "TRUE" ]
then
    echo "No differences between .case files generated via {Lata_to_med and then med2case} and {Lata_to_case} scripts"> my_text
fi


