#!/bin/bash

source $TRUST_ROOT/Outils/lata2dx/lata2dx/install/env.sh

mystudy=$1

mystudyLata=$mystudy".lata"
mystudyMed=$mystudy".med"
mystudyCase=$mystudy".case"
mystudyCase2=$mystudy"2.case"
mystudyLastTS=$mystudy"2_LastTS.case"

python $LATALOADER_ROOT/lib/Lata_to_med.py $mystudyLata $mystudyMed 1>/dev/null 2>&1
$MED_COUPLING_ROOT/bin/med2case $mystudyMed 1>/dev/null 2>&1
python $LATALOADER_ROOT/lib/Lata_to_case.py $mystudyLata $mystudyCase2 1>/dev/null 2>&1
python $LATALOADER_ROOT/lib/Lata_to_case.py -l $mystudyLata $mystudyLastTS 1>/dev/null 2>&1

all_files_are_here="FALSE"

if [ -e $mystudyLata ] && [ -e $mystudyMed ] && [ -e $mystudyCase ] && [ -e $mystudyCase2 ] && [ -e $mystudyLastTS ] 
then
    all_files_are_here="TRUE"
else
    touch nts_case1_all
    touch nts_case2_all
    touch nts_case2_last
fi


if [ $all_files_are_here == "TRUE" ]
then

    visit -cli -s script_visit.py $mystudyCase nts_case1_all -nowin 
    visit -cli -s script_visit.py $mystudyCase2 nts_case2_all -nowin 
    visit -cli -s script_visit.py $mystudyLastTS nts_case2_last -nowin 

    good="TRUE"
    for i in {0..6}
    do
	for field in VITESSE_SOM VITESSE_ELEM PRESSION_SOM PRESSION_ELEM
	do
	    file1=$mystudy"000"$i"."$field"_dom"
	    file2=$mystudy"2000"$i"."$field"_dom"

	    if [ ! -e $file1 ]
	    then
		echo "Error ! file "$file1" is missing ! ">my_text
		good="FALSE"
	    fi

	    if [ ! -e $file2 ]
	    then
      		echo "Error ! file "$file2" is missing ! ">my_text
		good="FALSE"
	    fi

	    if [ good == "TRUE" ]
	    then
		diff -u $file1 $file2 > differences
		touch empty

		diff differences empty
		status=$?
		if [ $status -ne 0 ]
		then
		    echo "Error !! There are differences between (at least) files "$file1" and "$file2> my_text
		    good="FALSE"
		fi 
		rm -f empty
	    fi

	done
    done

    if [ $good == "TRUE" ]
    then
	echo "No differences between .case files generated via {Lata_to_med and then med2case} and {Lata_to_case} scripts"> my_text
    fi
  
else
    echo "ERROR !!!!!! Not all files were generated !"> my_text
fi

