#!/bin/bash
quit()
{
   echo "Error."
   cat log
   exit -1
}

source $TRUST_ROOT/env_for_python.sh

mystudy=$1
mystudyLata=$mystudy".lata"
mystudyMed=$mystudy".med"
mystudyCase=$mystudy".case"
mystudyCase2=$mystudy"2.case"
mystudyLastTS=$mystudy"2_LastTS.case"

PATH_FILES=$TRUST_ROOT/exec/lata_tools/lib

python $PATH_FILES/Lata_to_med.py $mystudyLata $mystudyMed 		1>log 2>&1 || quit
$TRUST_MEDCOUPLING_ROOT/bin/med2case $mystudyMed			1>log 2>&1 || quit
python $PATH_FILES/Lata_to_case.py $mystudyLata $mystudyCase2 		1>log 2>&1 || quit
python $PATH_FILES/Lata_to_case.py -l $mystudyLata $mystudyLastTS 	1>log 2>&1 || quit

for file in $mystudyLata $mystudyMed $mystudyCase $mystudyCase2 $mystudyLastTS
do
   if [ ! -f $file ] || [ $file -ot ./verifie ]
   then
      echo "File $file not created !" && exit -1
   fi
done

good="TRUE"
for i in {0..1}
do
   for field in VITESSE_SOM VITESSE_ELEM PRESSION_SOM PRESSION_ELEM
   do
      file1=$mystudy"000"$i"."$field"_dom"
      file2=$mystudy"2000"$i"."$field"_dom"

      if [ ! -e $file1 ]
      then
	echo "Error ! file "$file1" is missing"
	exit -1
      fi

      if [ ! -e $file2 ]
      then
      	echo "Error ! file "$file2" is missing"
	exit -1
      fi

      diff -u $file1 $file2 > differences
      touch empty

      diff differences empty
      status=$?
      if [ $status -ne 0 ]
      then
	 echo "Error !! There are differences between (at least) files "$file1" and "$file2
	 good="FALSE"
	 exit -1
      fi 
      rm -f empty
   done
done

exit 0

