#!/bin/bash
# Creation du maillage mesh.med:
trust mesh 1>mesh.out_err 2>&1 || exit -1

# Creation de champs variables en temps dans le fichier fields.med:
#source $TRUST_ROOT/env_for_python.sh # si pas de MPI, impossible de charger env_for_python.sh
source $TRUST_MEDCOUPLING_ROOT/env.sh
python ./prepare.py || exit -1

# Dump du field.med cree:
echo -e "1\n1\n0\n" | $TRUST_ROOT/lib/src/LIBMED/bin/mdump --structure fields.med

