#!/bin/bash
export project_directory=$TRUST_ROOT/Validation/Rapports_automatiques/Verification/PolyMAC
source "$project_directory/share/maquette_decapoly/env_maquette.sh"
python prepare_python.py
for cas in */*/maillage_* ; do cp post_run ${cas}/. ; done
python $TRUST_ROOT/bin/KSH/preprocessor.py poiseuille.prm.P poiseuille.prm
