#!/bin/bash
# Check fieldsplit
if [ ! -f fieldsplit.TU ] || [ poise_VEF.TU -nt fieldsplit.TU ]
then
   echo "Checking fieldsplit precond:"
   trust fieldsplit 1>fieldsplit.out 2>fieldsplit.err
   compare_lata poise_VEF.lml fieldsplit.lml || exit -1
   echo "poise_VEF:"
   grep "solveurs A" poise_VEF.TU
   echo "poise_VEF with pcfieldsplit:"
   grep "solveurs A" fieldsplit.TU
fi
