#!/bin/bash
# Check fieldsplit
if [ ! -f additive.TU ] || [ poise_VEF.TU -nt additive.TU ] || [ verifie -nt poise_VEF.TU ]
then
   echo "Checking PCFIELDSPLIT preconditioner (block solvers):"
   for type in multiplicative additive schur no
   do
      trust $type 1>$type.out_err 2>&1
      compare_lata poise_VEF.lml $type.lml 1>$type.log 2>&1 
      [ $? != 0 ] && cat $type.log && exit -1
      echo "poise_VEF with $type pcfieldsplit :"
      grep "solveurs A" $type.TU
      grep "MatMult " $type"_petsc.TU"
   done
fi
