#!/bin/bash
if [ ! -d cond_coup_fictif_vdf_impl ]
then
   copie_cas_test cond_coup_fictif_vdf_impl || exit -1
fi

if [ ! -d cond_coup_fictif_vef_impl ]
then
   copie_cas_test cond_coup_fictif_vef_impl || exit -1
fi

if [ ! -d cond_couple_vdf_impl ]
then
   copie_cas_test cond_couple_vdf_impl || exit -1
fi

if [ ! -d cond_couple_vef_impl ]
then
   copie_cas_test cond_couple_vef_impl || exit -1
else
   exit 0
fi
