#!/bin/bash

declare -A dico_meshes_2d=(["Cartesian"]="1 2 3" # 4 5 6 7"
                           ["Locally_Refined"]="1 2 3" # 4 5 6 7"
                           ["Quadrangles"]="1 2 3" # 4 5 6 7"
                           ["Triangles"]="1 2 3") # 4 5 6")

meshes="${!dico_meshes_2d[@]}"
meshes="Triangles Quadrangles Cartesian Locally_Refined"
echo $meshes > listmeshes
sed "s/%meshes%/$meshes/" conv.prm.P.m > conv.prm.P

python $TRUST_ROOT/bin/KSH/preprocessor.py conv.prm.P conv.prm
share=$TRUST_ROOT/Validation/Rapports_automatiques/Verification/PolyMAC/share

echo > ll
for mesh in $meshes
do
    for n in ${dico_meshes_2d[$mesh]}
    do
        mkdir -p $mesh/jdd_$n
        sed -i "/# bloc testcases #/ i\ TestCase $mesh/jdd_$n cas.data" conv.prm
        meshname=$share/meshes/$mesh/jdd_$n/mesh.med
        sed "s~__meshprerun__~$meshname~g" pre_run > $mesh/jdd_$n/pre_run
        cp jdd.data $mesh/jdd_$n/cas.data
        cp post_run $mesh/jdd_$n/post_run
        echo $mesh/jdd_${n}/cas.data >> ll
    done
done

grep -v _1 ll > liste_cas_exclu_nr
