//
// Warning : DO NOT EDIT !
// To update this file, run: make depend
//
#include <verifie_pere.h>
#include <ArrOfBit.h>
#include <ArrOfDouble.h>
#include <ArrOfFloat.h>
#include <ArrOfInt.h>
#include <Constante.h>
#include <DescStructure.h>
#include <Descripteur.h>
#include <DoubleTab.h>
#include <DoubleTabs.h>
#include <DoubleTrav.h>
#include <DoubleVect.h>
#include <DoubleVects.h>
#include <Esp_Dist.h>
#include <Esp_Virt.h>
#include <FloatTab.h>
#include <IntTab.h>
#include <IntTrav.h>
#include <IntVect.h>
#include <IntVects.h>
#include <MD_Vector_composite.h>
#include <MD_Vector_std.h>
#include <Parser_U.h>
#include <Polynome.h>
#include <RTabInt.h>
#include <StdFunction.h>
#include <Table.h>
#include <UserUnaryFunction.h>
void instancie_src_Kernel_Math() {
Cerr << "src_Kernel_Math" << finl;
ArrOfBit inst1;verifie_pere(inst1);
ArrOfDouble inst2;verifie_pere(inst2);
ArrOfFloat inst3;verifie_pere(inst3);
ArrOfInt inst4;verifie_pere(inst4);
Constante inst5;verifie_pere(inst5);
DescStructure inst6;verifie_pere(inst6);
Descripteur inst7;verifie_pere(inst7);
DoubleTab inst8;verifie_pere(inst8);
DoubleTabs inst9;verifie_pere(inst9);
DoubleTrav inst10;verifie_pere(inst10);
DoubleVect inst11;verifie_pere(inst11);
DoubleVects inst12;verifie_pere(inst12);
Esp_Dist inst13;verifie_pere(inst13);
Esp_Virt inst14;verifie_pere(inst14);
FloatTab inst15;verifie_pere(inst15);
IntTab inst16;verifie_pere(inst16);
IntTrav inst17;verifie_pere(inst17);
IntVect inst18;verifie_pere(inst18);
IntVects inst19;verifie_pere(inst19);
MD_Vector_composite inst20;verifie_pere(inst20);
MD_Vector_std inst21;verifie_pere(inst21);
Parser_U inst22;verifie_pere(inst22);
Polynome inst23;verifie_pere(inst23);
RTabInt inst24;verifie_pere(inst24);
Sin inst25;verifie_pere(inst25);
Asin inst26;verifie_pere(inst26);
Cos inst27;verifie_pere(inst27);
Acos inst28;verifie_pere(inst28);
Tan inst29;verifie_pere(inst29);
Atan inst30;verifie_pere(inst30);
Ln inst31;verifie_pere(inst31);
Exp inst32;verifie_pere(inst32);
Sqrt inst33;verifie_pere(inst33);
Int inst34;verifie_pere(inst34);
Erf inst35;verifie_pere(inst35);
Rnd inst36;verifie_pere(inst36);
Cosh inst37;verifie_pere(inst37);
Sinh inst38;verifie_pere(inst38);
Tanh inst39;verifie_pere(inst39);
Atanh inst40;verifie_pere(inst40);
Not inst41;verifie_pere(inst41);
Abs inst42;verifie_pere(inst42);
Sgn inst43;verifie_pere(inst43);
Table inst44;verifie_pere(inst44);
UserUnaryFunction inst45;verifie_pere(inst45);
}
