#!/bin/bash
plugin=$1
if [ -z "$TRUST_ROOT" ]
then
	ROOT=`pwd`/../..
	echo "Not in TRUST environment. Rootdir=$ROOT"
	
	local=$ROOT/bin

else
	ROOT=$TRUST_ROOT
       	echo "TRUST environment found. Rootdir=$ROOT"

	local=$ROOT/exec/VisIt/bin

fi

[ $0 -nt build ] && rm -rf build 
if [ ! -d build ]
then
   echo Creating build directory
   mkdir -p build
   cd build
   echo Creating symlink to source files
   ln -sf ../src/* . 2>/dev/null
   $local/xml2info triofield.xml
  
   $local/xml2cmake triofield.xml
       
   dlocal=`dirname $local`
   echo $dlocal
   sed "s?$HOME/.visit/2.?$dlocal/2.?;s?$HOME/.visit?$dlocal/current?" CMakeLists.txt > p
	# tkdiff  CMakeLists.txt p
   mv p  CMakeLists.txt
   rm -f CMakeCache*
   cmake . -DCMAKE_CXX_COMPILER=$TRUST_CC -DCMAKE_C_COMPILER=$TRUST_cc

   # fin modif makefile
  
else
   cd build
fi

#######################
# Compilation du plugin
#######################
make
