#!/bin/bash
plugin=$1
if [ -z "$TRUST_ROOT" ]
then
	ROOT=`pwd`/../..
	echo "Not in TRUST environment. Rootdir=$ROOT"
	
	local=$ROOT/bin

else
	ROOT=$TRUST_ROOT
       	echo "TRUST environment found. Rootdir=$ROOT"

	local=$ROOT/Outils/VisIt/bin

fi


if [ ! -d build ]
then
   echo Creating build directory
   mkdir -p build
   cd build
   echo Creating symlink to source files
   ln -sf ../src/* . 2>/dev/null
   $local/xml2info triofield.xml
  
   $local/xml2cmake triofield.xml
       
   dlocal=`dirname $local`
   echo $dlocal
   sed "s?$HOME/.visit/2.?$dlocal/2.?;s?$HOME/.visit?$dlocal/current?" CMakeLists.txt > p
	# tkdiff  CMakeLists.txt p
   mv p  CMakeLists.txt
   rm -f CMakeCache*
   cmake . -DCMAKE_CXX_COMPILER=$TRUST_CC_BASE  -DCMAKE_C_COMPILER=$TRUST_cc_BASE

   # fin modif makefile
  
else
   cd build
fi

#######################
# Compilation du plugin
#######################
make

# Mise en gestion de configuration si necessaire
if [ -z "$TRUST_ROOT" ]
then
	exit
fi

cd $TRUST_ROOT/Outils/VisIt
if [ "$plugin" != "" ]
then
   ARCH=`echo $plugin | $TRUST_Awk -F. '{print $2}'`
   update=0
   if [ -f $plugin ]
   then
      TMP=`mktemp_ -d`
      mkdir $TMP
      cd $TMP
      gunzip -c $TRUST_ROOT/Outils/VisIt/$plugin > tmp.tar
      tar xf tmp.tar
      # Bizarrerie, je compare les .so car si je compare les .tar.gz les tailles changent de facon aleatoire...
      for lib in `ls current/*/plugins/databases/*lataData*.so 2>/dev/null`
      do
         [ "`diff $lib $TRUST_ROOT/Outils/VisIt/$lib`" != "" ] && update=1
      done
      rm -r -f $TMP
      cd -
   else
      update=1
   fi
   if [ $update = 1 ]
   then
      old=`ls plugin*"."$ARCH.tar.gz 2>/dev/null | grep -v $plugin`
      if [ "$old" != "" ]
      then
	 CHECKOUT . 1>/dev/null 2>&1
	 cleartool mv $old $plugin
      fi
      [ "$MA_VUE" != "" ] && CHECKOUT $plugin 1>/dev/null 2>&1
      tar cf tmp.tar current/$ARCH/plugins/databases/*triofieldData*.so
      gzip -f tmp.tar
      mv -f tmp.tar.gz $plugin
      echo "$plugin mis a jour."
   fi
fi
