#!/bin/bash
DIR=`dirname $0`
DIR=`(cd $DIR;pwd)`
plugin=$1
if [ -z "$TRUST_ROOT" ]
then
	ROOT=`pwd`/../..
	echo "Not in TRUST environment. Rootdir=$ROOT"
	
	local=$ROOT/bin

else
	ROOT=$TRUST_ROOT
       	echo "TRUST environment found. Rootdir=$ROOT"

	local=$ROOT/exec/VisIt/bin

fi

Build=$TRUST_ROOT/build/Outils/VisIt/plugins/triofield/build
[ $0 -nt ${Build} ] && rm -rf ${Build} 
if [ ! -d ${Build} ]
then
   echo Creating ${Build} directory
   mkdir -p ${Build}
   cd ${Build}
   echo Creating symlink to source files
   ln -sf $DIR/src/* . 2>/dev/null

   env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2info triofield.xml
   env LD_LIBRARY_PATH=$TRUST_ROOT/exec/python/lib:$LD_LIBRARY_PATH $local/xml2cmake triofield.xml
       
   dlocal=`dirname $local`
   echo $dlocal
   sed "s?$HOME/.visit?$dlocal?" CMakeLists.txt > p
   #sed "s?$HOME/.visit/2.?$dlocal/2.?;s?$HOME/.visit?$dlocal/current?" CMakeLists.txt > p
	# tkdiff  CMakeLists.txt p
   mv p  CMakeLists.txt
   rm -f CMakeCache*
   $TRUST_ROOT/exec/python/bin/cmake . -DCMAKE_CXX_COMPILER=$TRUST_CC -DCMAKE_C_COMPILER=$TRUST_cc

   # fin modif makefile
  
else
   cd ${Build}
fi

#######################
# Compilation du plugin
#######################
make || exit -1
(cd ../../.. ; rm -rf plugins)

