#!/bin/bash

file_res2='wl_res2_pb_Diffusion_chaleur.out'
file_res7='wl_res7_pb_Diffusion_chaleur.out'
file_res25='wl_res25_pb_Diffusion_chaleur.out'

nc_bas=4
nc_haut=5

val_bas_res2=`awk -v nc_bas=$nc_bas ' END{print $nc_bas}' $file_res2`
val_bas_res7=`awk -v nc_bas=$nc_bas ' END{print $nc_bas}' ../wl_res7/$file_res7`
val_bas_res25=`awk -v nc_bas=$nc_bas ' END{print $nc_bas}' ../wl_res25/$file_res25`

val_haut_res2=`awk -v nc_haut=$nc_haut ' END{print $nc_haut}' $file_res2`
val_haut_res7=`awk -v nc_haut=$nc_haut ' END{print $nc_haut}' ../wl_res7/$file_res7`
val_haut_res25=`awk -v nc_haut=$nc_haut ' END{print $nc_haut}' ../wl_res25/$file_res25`

echo $val_bas_res2 $val_bas_res7 $val_bas_res25 > val_wl_out
