#!/bin/bash
# Comparaisons avec le format actuel du LATA
echo "Checking current LATA format with LATA MPI-IO written..."
if [ -f PAR_Lata.lata ] && [ PAR_Lata.lata -nt Lata.lata ]
then
   compare_lata PAR_Lata.lata PAR_Lata_actuel.lata 1>verifie.log 2>&1 || exit -1
else
   compare_lata Lata.lata Lata_actuel.lata 1>verifie.log 2>&1 || exit -1
fi
exit 0
