#!/bin/ksh
exec=$1
[ ! -x $1 ] && echo usage $0 Trio_u_code
b=""
[ "`basename $0`" = "testP_S" ] && b="S_"
[ "`basename $0`" = "testP_VEF" ] && b="VEF_"
[ "`basename $0`" = "testP_S_VEF" ] && b="S_VEF_"
cat /dev/null > ${b}resP
list="0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9"
[ "$2" != "" ] && list=$2
for eps in $list
do
unpe=`echo 1 + $eps| bc`
unme=`echo 1 - $eps | bc`
cas=${b}eps_${eps}
sed "s/unpe/$unpe/
     s/unme/$unme/ " ${b}base.data > $cas.data
#vi $cas.data
$exec $cas
Pc=`grep -A2 pression_thermo ${cas}_pb.sauv | tail -1 | sed "s/fin//"`
Pe=`grep ${eps}00 ${b}sol_Pc | awk '{print $2}'`

echo "( $Pc - $Pe )/ ($Pc + $Pe ) *2 "

err=`echo 1 | awk -v Pc=$Pc -v Pe=$Pe  '{print (( Pc - Pe )/ (Pc + Pe ) *2)}'  `
echo $eps $Pc  $Pe $err >> ${b}resP
done
xmgrace -nxy ${b}resP&
