#!/bin/bash
if [ "$TRUST_DISABLE_MPI" != 1 ]
then
   trust cond_vef_impl_mod || exit -1
   make_PAR.data cond_vef_impl_mod 
   trust PAR_cond_vef_impl_mod 2
else
   trust cond_vef_impl_mod || exit -1
fi