#!/bin/bash
package=$1

path_package=$TRUST_ROOT/externalpackages/$package.tar.gz
[ ! -f $path_package ] && echo "$path_package not found! Update your makefile." && exit -1

build_root=$TRUST_TMP/build/lib
mkdir -p $build_root
cd $build_root
gunzip -c $path_package > $package.tar
tar xf $package.tar
rm -f $package.tar
Vc_dir=`ls | grep Vc 2>/dev/null`
[ "$Vc_dir" = "" ] && echo "Vc dir not found." && exit -1

install_dir=$TRUST_ROOT/lib/src/LIBVC
build_dir=$build_root/Vc_build
mkdir -p $build_dir
cd $build_dir
cmake ../$package -DCMAKE_INSTALL_PREFIX=$install_dir -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$TRUST_cc_BASE -DCMAKE_CXX_COMPILER=$TRUST_CC_BASE
 
# Compilation
$TRUST_MAKE

# Installation
make install

status=$?
if [ $status -ne 0 ]; then
    echo "[ERROR] Installation of Vc failed. You can disable it with ./configure -disable-vc"
    exit -1
fi


exit 0
