#!/bin/bash
copie_cas_test cpu_3D || exit -1
mv cpu_3D/cpu_3D.data .
sed "s/precond/save_matrice precond/" cpu_3D.data > mod.data 

if [ "$TRUST_DISABLE_MPI" != 1 ]
then
   trust mod || exit -1
   make_PAR.data mod
   trust PAR_mod 2
else
   trust mod || exit -1
fi