#!/bin/bash

cas=conduc_var_KO

trust ${cas} 1>${cas}.out 2>${cas}.err
status=$?
if [ $status -eq 0 ]
    then
    echo ERROR: le cas test ${cas} devrait planter
    exit 1
fi
if [ "`grep 'ERROR: Conduction equation: one of the physical properties rho ou Cp' ${cas}.err`" == "" ]
then
    echo ERROR: le cas test ${cas} devrait afficher un warning
    exit 1
fi

exit 0
