#!/bin/bash

trust domaine.data 1>domaine.out 2>domaine.err
mv Mesh_1_0000.med Mesh_1.med


source $TRUST_ROOT/exec/lata2dx_install/env.sh

if [ -f Cond_Field_Anis_NonUniform.py ]
then
  python Cond_Field_Anis_NonUniform.py
fi

if [ -f Cond_Field_Iso_NonUniform.py ]
then
  python Cond_Field_Iso_NonUniform.py
fi
