#!/bin/bash
# si pas petsc on change de solveur
if [ "$TRUST_DISABLE_PETSC" = "1" ]
then
   echo "Disabling petsc in docond_VEF.data"
   grep -v petsc docond_VEF.data > p.data
   mv p.data docond_VEF.data
fi
# Lancement du calcul couple TRUST:
source $TRUST_ROOT/env_TRUST.sh
data=docond_VEF
trust $data 1>ok.out 2>ok.err
if [ $? -eq 0 ]
then
  echo OK > is_ok
else
  rm -f is_ok
fi
#touch ok.data
mv -f $data.TU ok.TU
