#!/bin/bash
echo usage cas numero
cas=$1
casb=`basename $cas`
numero=$2
DIR=`dirname $0`
rm -rf test_[1-9] testref_[1-9]
DIR=`(cd $DIR;pwd)`
tar zxvf test2.tgz
[ -d test_$numero ] && echo $numero existe deja && exit 
[ ! -f $cas ] && echo $cas introuvable && exit
mkdir -p test_$numero/model
mkdir -p testref_$numero
cp $cas  test_$numero/model
cd test_$numero/model
$DIR/xprepro  $casb 2
mv ../prepro ../../testref_$numero
cd ../../
rm -rf test_$numero/model
mkdir -p test_$numero/model
cp $cas  test_$numero/model
cd testref_$numero/prepro/trans_geom
ici=`pwd`
echo $ici
[ `basename $ici ` != "trans_geom" ] &&xterm&& exit
rm -f *[1-9] 
ln -s ../Probleme[1-9]/*[1-9].
cd ../../..
tar zcvf test2_new.tgz test_[1-9] testref_[1-9]
