#!/bin/bash
sortie=$1
[ "$1" = "" ] && sortie=mod.py
get_morc()
{
l=`grep -n "# marqueur" $1 | head -$i | tail -1   | $TRUST_Awk -F: '{print $1}'`
let i2=$i-1
l2=`grep -n "# marqueur" $1 | head -$i2 | tail -1   | $TRUST_Awk -F: '{print $1}'`
[ "$l2" = "" ] && l2=0
let l3=$l-$l2
#echo $1 $2 $l $l2 $l3

head -$l $1 | tail -$l3 
}
l=`grep -n "B0=" intersect.py | head -1 | $TRUST_Awk -F: '{print $1}'`
n=`wc -l intersect.py| $TRUST_Awk '{print $1}'`
d=`echo $n - $l +1 | bc`
echo $l $n $d
tail -$d intersect.py > pr.py
l=`echo $l -1 | bc `
head -$l intersect.py > pr2.py
#cat pr2.py
nbmarq=`grep "# marqueur" es.py | wc -l | $TRUST_Awk '{print $1}'`
echo $nbmarq
#let nbmarq=$nbmarq+1
let i=1
cat /dev/null > $sortie
while [ $i -le $nbmarq ]
do
for file in es.py pr2.py pr.py
do
get_morc $file $i >> $sortie
done
let i=$i+1
done
rm pr2.py pr.py
dernier=`grep ExportBREP $sortie | tail -2 | head -1 | $TRUST_Awk -F\" '{print $2}'`
dernier=`basename $dernier .brep`
nom=`basename $sortie .py`
echo $ECHO_OPTS "1,$ s?$dernier?$nom?g\nwq"
echo $ECHO_OPTS "1,$ s?$dernier?$nom?g\nwq" | ed $sortie
liste=`grep macro $sortie | grep Import | $TRUST_Awk -F\" '{print $2}'`
echo $liste 
BASE=`dirname $0`
for mac in $liste 
do
echo $mac
mac2=`basename $mac .brep`
echo $mac $mac2
$BASE/traduction ${mac2}.trace
sh $0 ${mac2}.py
done
#$TRUST_Awk 'BEGIN { f1="es.py";f2="intersect.py";f3="pr.py";f=f1} {print FILENAME}'  es.py

#$TRUST_Awk 'BEGIN {f1="es.py";f2="intersect.py";f3="pr.py";f=f1} /# marqueur/ {if (FILENAME==f1) { FILENAME=f2;print f2;print FILENAME } else { if (FILENAME==f2) { FILENAME=f3 } else { FILENAME=f1} } } !/# marqueur/ {print $0} ' es.py intersect.py
