#!/bin/bash
# Procedure de test de Xprepro
echo "Usage: `basename $0` [numero_cas_test]"
[ ${#DISPLAY} = 0 ] && export DISPLAY=":0"
# on test wish
echo "exit" > test.wish
wish_notok=0
log=`$WISH test.wish 2>&1`

# `$WISH test.wish   wish_notok=$? ne marche pas
[ "$log" != "" ] && echo $log && wish_notok=1

if [ $wish_notok -eq 0 ]
then
   echo $WISH Ok
else
   echo $WISH KO , pb avec DISPLAY ?
   echo "XPREPRO=KO" && exit -1
fi
#
[ ! -f $exec ] && echo "$exec non existant." && exit -1
DIR=`dirname $0`
DIR=`(cd $DIR; pwd)`
gunzip -f -c test2.tgz | tar -xf -
listdir=`ls -d test_[1-9]`
[ "$1" != "" ] && listdir=test_$1
oktot=0
log=$DIR/testfort2.log
cat /dev/null > $log
for dirt in $listdir
do
   cd $DIR
   rm -r -f $DIR/test $DIR/testref
   echo $ECHO_OPTS "Xprepro: $dirt \c"
   mv $dirt test
   dirt2=`echo $dirt | sed "s/test/testref/"`
   mv $dirt2 testref
   cd $DIR/test/model
   fileprep=`ls *.prep`
   $DIR/initprepro `pwd`
   cas=`basename $fileprep .prep` 
   #$DIR/xprepro $fileprep 2 1>>$log 2>&1
   files_code="defineh_inc appelrac.h appeldec.h appel.h decl_appel.h decl_appeldec.h decl_appelrac.h maillage$cas routinesupp$cas infosupp$cas noms_des_bords$cas "
   code_not_ok=0
   if [ $wish_notok -eq 0 ]
   then 
      $DIR/xprepro $fileprep code 1>>$log 2>&1
      # il faut verifier que les fichiers generes sont corrects
      for file in $files_code
      do
         if [ -f $file ]
         then
            if [ "`diff ../../testref/model/$file . 2>&1`" != "" ] 
            then
	       echo  "pb avec $file different"
	       echo "diff ../../testref/model/$file . " 1>>$log 2>&1
               diff ../../testref/model/$file . 1>>$log 2>&1
	       code_not_ok=1
            fi
         fi
      done
   else
      for file in $files_code 
      do
         [ -f ../../testref/model/$file ] && cp ../../testref/model/$file .
      done
   fi
   $DIR/exec_model_linux2 -no_xterm 0 $cas 1>>$log 2>&1
   $DIR/exec_prepro2 -no_xterm `pwd` $fileprep 1 1>>$log 2>&1
   #$DIR/exec_prepro2 `pwd` $fileprep 1
   DIR2=`head -1 $DIR/testref/prepro/trans_geom/infobord1 | awk '{print $1}'`
   DIR2=`dirname $DIR2`
   #echo $DIR2
   if [ ! -d ../prepro/trans_geom ]
   then
      err=1
   else
      cd ../prepro/trans_geom
      DIR1=`head -1 infobord1 | awk '{print $1}'`
      DIR1=`dirname $DIR1`
      DIR1=`dirname $DIR1`
      for file in `ls infobord*` 
      do
         sed "s?${DIR1}/test?${DIR2}?g" $file >$file.p
         cat $file.p > $file
         rm $file.p
      done
      sed "s/_bin//" trans_geom.data | sed "s/bin//" > trans_geom2.data
      $exec trans_geom2 1>>$log 2>&1
      cd $DIR/testref/prepro/trans_geom
      sed "s/_bin//" trans_geom.data | sed "s/bin//" > trans_geom2.data
      $exec trans_geom2 1>>$log 2>&1
      #echo "executer testfin apres avoir fait model prepro"
      cd $DIR
      echo cas $fileprep 1>>$log
      ./testfin 1>>$log
      err=$?
   fi
   if [ $code_not_ok -ne 0 ] 
   then
      if [ $err -eq 0 ]
      then
         echo "execution OK, mais code genere different ! "
         echo "il faut corriger pour tester la portabilite"
      fi
      err=$code_not_ok 
   fi
   [ -d $DIR/$dirt".log"  ] && rm -rf $DIR/$dirt".log"
   [ -d $DIR/$dirt2".log" ] && rm -rf $DIR/$dirt2".log"
   if [ $err -ne 0 ]
   then 
      echo "Erreur, pour analyse on copie les tests en "$dirt".log et "$dirt2".log" | tee -a $log
      cp -R $DIR/test $DIR/$dirt".log"
      cp -R $DIR/testref $DIR/$dirt2".log"
      errtot=1
   else
      errtot=0
      echo "OK"
   fi
   #rm -r -f $DIR/test $DIR/testref
done
# il en reste encore 1 
rm -r -f $DIR/test $DIR/testref
echo "See $log file if error."
if  [ $errtot != 0 ]
then
   echo "XPREPRO=KO"
else
   echo "XPREPRO=OK"
fi
exit $errtot
