#!/bin/bash
DIR=`dirname $0`
DIR=`(cd $DIR; pwd)`
gunzip -f -c test.tar.gz | tar -xf -
cd $DIR/test/model
$DIR/initprepro `pwd`
$DIR/exec_model_linux2 0 plan
$DIR/exec_prepro2 `pwd` plan.prep 1

#echo "executer testfin apres avoir fait model prepro"
cd $DIR
./testfin

