#!/bin/bash
DIR=`dirname $0`
DIR=`(cd $DIR;pwd)`

trad=$DIR/traduction
[ ${#TRUST_CC} = 0 ] && TRUST_CC=g++
if  [ ! -f $trad ] || [ $trad.cpp -nt $trad ] 
then
 $TRUST_CC -g -o $trad $DIR/traduction.cpp
#  g++ -g -o traduction traduction.cpp -ftest-coverage -fprofile-arcs
fi
[ ! -f $trad ] && echo "WARNING no translation tool found" &&exit
Catpy=$DIR/Catpy
echo $trad
#PL: Pour debugger le traducteur:
#valgrind --db-attach=yes $trad $1
list_vol=`$trad $1 2>/dev/null| grep "list in"| awk '{print $NF}'`
echo "liste vol" $list_vol
[ "$list_vol" = "" ] && echo "WARNING no volumes found "

name=`basename $1 .trace`
verif="monSolide "
cat /dev/null > $name.py
for volume in $list_vol
do
   echo "volume $volume..."
   if [ $volume -ne 0 ]
   then
      v=$volume
      if [ $v -lt 0 ] 
      then
         let v=0-v
         v="m"$v
      else
         $trad $1 $volume
         mv testc2 testc2_$v
         sh $Catpy ${name}_$v.py
	 echo "try:">>$name.py
	 echo "  reload(${name}_$v)" >>$name.py
         echo "except:">>$name.py
         echo "  import ${name}_$v" >>$name.py
         verif=$verif" "${name}_$v.brep" "$volume
      fi
   fi
done
#echo $verif
