#!/bin/bash
echo "Tcl/Tk utilise: "$WISH
[ ${#DISPLAY} = 0 ] && export DISPLAY=":0"
[ ! -f "$WISH" ]  && echo "Tck/Tk is not available on your computer. You cannot use Xprepro." && exit
DIR=`dirname $0`
DIR=`(cd $DIR; pwd)`
if [ "$1" != "" ]
then
   dir=`dirname $1`
   file=`basename $1`
   cd $dir
   exec $WISH $DIR/xprepro.tcl $file $2
else
   exec $WISH $DIR/xprepro.tcl
fi
#$TRUST/ROOT/bin/IHM/Erreur.ihm toto
#wait $!
