#!/bin/bash
jdd=$1
# ToDo comparer lml a des references dans chaque repertoire
for rep in `ls | grep calcul`
do
   cd $rep
   # Verifie que les fichiers de postraitement sont complets (en tete surtout):
   grep TRUST $jdd.lata 	1>/dev/null 2>&1 || exit -1 	# lata
   grep GEOM $jdd.lata 		1>/dev/null 2>&1 || exit -1 	# lata
   grep $jdd *.son 		1>/dev/null 2>&1 || exit -1 	# son
   grep temps $jdd.dt_ev 	1>/dev/null 2>&1 || exit -1 	# dt_ev
   echo "$rep:"`wc -l $jdd.dt_ev`
   cd - 2>/dev/null
done
