//TRUST_NO_INDENT
/****************************************************************************
* Copyright (c) 2015 - 2016, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
//
// File      : Coarsen_Operator_Uniform.h
// Directory : $IJK_ROOT/src/IJK/solveur_mg
//
/////////////////////////////////////////////////////////////////////////////
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file Coarsen_Operator_Uniform.h.P
//
#ifndef Coarsen_Operator_Uniform_included
#define Coarsen_Operator_Uniform_included

#include <Coarsen_Operator_base.h>

// Refine all cells by factor 2 in K, JK or IJK directions
class Coarsen_Operator_Uniform : public Coarsen_Operator_base
{
  Declare_instanciable(Coarsen_Operator_Uniform);
 public:
  void initialize_grid_data(const Grid_Level_Data_double & fine, Grid_Level_Data_double & coarse,
			    int additional_k_layers) override;
  void coarsen(const IJK_Field_double & fine, IJK_Field_double & coarse, int compute_weighted_average = 0) const override;
  void interpolate_sub_shiftk(const IJK_Field_double & coarse, IJK_Field_double & fine, const int kshift) const override;
  void initialize_grid_data(const Grid_Level_Data_float & fine, Grid_Level_Data_float & coarse,
			    int additional_k_layers) override;
  void coarsen(const IJK_Field_float & fine, IJK_Field_float & coarse, int compute_weighted_average = 0) const override;
  void interpolate_sub_shiftk(const IJK_Field_float & coarse, IJK_Field_float & fine, const int kshift) const override;
 protected:
  void ajouter_param(Param & param) override;
  // By how much shall we coarsen in each direction ?
  ArrOfInt coarsen_factors_;
};
#endif
