//TRUST_NO_INDENT
/****************************************************************************
* Copyright (c) 2015 - 2016, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
//
// File      : SSE_kernels.h
// Directory : $IJK_ROOT/src/IJK/solveur_mg
//
/////////////////////////////////////////////////////////////////////////////
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file SSE_kernels.h.P
//
#ifndef SSE_kernels_included
#define SSE_kernels_included
#include <IJK_Field.h>
#include <Interprete.h>

      // ToDo: remove it! Temporary way to respect trust rules (name of the file = name of the class)
   class SSE_kernels
   {
public:
     SSE_kernels() {}
    ~SSE_kernels() {}
   };

   
class Test_SSE_Kernels : public Interprete
{
  Declare_instanciable(Test_SSE_Kernels);
 public:
  Entree & interpreter(Entree & is) override;
  
};


void Multipass_Jacobigeneric_float(IJK_Field_local_float & x,
				     IJK_Field_local_float & residue,
				     const IJK_Field_local_float & coeffs,
				     const IJK_Field_local_float & secmem,
				     const int npass,
				     const bool last_pass_is_residue,
				     const float relax_coefficient);
void reference_kernel_float(const IJK_Field_local_float & tab, const IJK_Field_local_float & coeffs, const IJK_Field_local_float & secmem, IJK_Field_local_float & resu, 
			  const float relax, const bool residue);
void Multipass_Jacobigeneric_double(IJK_Field_local_double & x,
				     IJK_Field_local_double & residue,
				     const IJK_Field_local_double & coeffs,
				     const IJK_Field_local_double & secmem,
				     const int npass,
				     const bool last_pass_is_residue,
				     const double relax_coefficient);
void reference_kernel_double(const IJK_Field_local_double & tab, const IJK_Field_local_double & coeffs, const IJK_Field_local_double & secmem, IJK_Field_local_double & resu, 
			  const double relax, const bool residue);
#endif
