#!/bin/bash
echo "Usage: run_test [-lata] [-no_gui] [test.data]"
[ ${#TRUST_ROOT} = 0 ] && echo "TRUST_ROOT not set." && exit -1
format=visit && [ "$1" = -lata ] && shift && format=lata
gui=1 && [ "$1" = -no_gui ] && shift && gui=0
liste=`ls *.data | grep -v _Post_Meshtv`
[ ${#1} != 0 ] && liste=$1
for file in $liste
do
   cas=${file%.data}
   NP=""
   if [ $cas = "M3DLAM" ] && [ "$TRUST_DISABLE_MPI" != 1 ]
   then
      NP=4
      make_PAR.data M3DLAM $NP 1>/dev/null 2>&1
      triou DEC_M3DLAM 1>/dev/null 2>&1
      cas=PAR_M3DLAM
   fi
   if [ $format = lata ]
   then
      echo $ECHO_OPTS "1,$ s?format lml?format lata?g\nw lata_$cas.data" | ed $cas.data 1>/dev/null 2>&1
      cas=lata_$cas.data
      echo $ECHO_OPTS "1,$ s?vitesse elem?vitesse elem vitesse faces?g\nw" | ed $cas.data 1>/dev/null 2>&1
      echo $ECHO_OPTS "1,$ s?vitesse som?vitesse som vitesse faces?g\nw" | ed $cas.data 1>/dev/null 2>&1
   fi
   # Menage
   rm -f *.$format
   echo $ECHO_OPTS "Cas $cas : \c"
   triou $cas $NP 1>$cas.out 2>$cas.err
   [ $? != 0 ] && echo "Erreur du calcul pour le cas test $cas" && exit -1
   echo "OK"
   # Verifie s'il y'a des erreurs de type DB pour visit
   [ $format = visit ] && $TRUST_Awk 'BEGIN {db=0} /DB/ {db++} END {print "Erreurs type DB...:"db}' $cas.err

   # Lancement de Visit eventuel
   file=`ls -rt *.$format`
   [ "$file" = "" ] && echo "Aucun fichier $format cree pour $cas." && exit -1
   [ $gui = 1 ] && visit -o $file
   
   # Menage
   rm -f *_M3DLAM.data
done
rm -f *.rep
