#!/bin/bash
jdd=`pwd`
jdd=`basename $jdd`
if [ "$TRUST_DISABLE_MPI" != 1 ]
then
   make_PAR.data sauve
   NP=$?
   echo $ECHO_OPTS "1,$ s? $jdd? PAR_$jdd?g\nw" | ed PAR_sauve.data
   trust PAR_sauve $NP || exit -1
fi

