#!/bin/bash
name=$1 && [ "$1" = "" ] && exit -1
cible=$2 && [ "$2" = "" ] && exit -1
if [ "$TRUST_BUILD_IN_TMP" = "1" ]
then

    build_dir=$TRUST_TMP/build/cmake
    mkdir -p $build_dir
    cp * $build_dir
    cd $build_dir
fi
name=${name%.tar.gz}
rm -r -f $name
echo $name
gunzip -f -c  $TRUST_ROOT/externalpackages/$name.tar.gz | tar -xf -
rm -f $name.tar
cd $name || exit -1
./configure --prefix=$cible
$TRUST_MAKE || exit -1
make install || exit -1
cd ..
rm -r -f $name
