#!/bin/bash
name=$1 && [ "$1" = "" ] && exit -1
cible=$2 && [ "$2" = "" ] && exit -1
name=${name%.tar.gz}
rm -r -f $name
echo $name
gunzip -f -c  $TRUST_ROOT/externalpackages/$name.tar.gz | tar -xf -
rm -f $name.tar
cd $name || exit -1
./configure --prefix=$cible
$TRUST_MAKE || exit -1
make install || exit -1
cd ..
rm -r -f $name
