#!/bin/bash
# OpenMPI install script
default_version=2.0.4
latest_version=4.1.0
version=$default_version
# Cas ou l'on force la version la plus recente:
[ "$TRUST_FORCE_LATEST_OPENMPI" = 1 ] && version=$latest_version

options=""
# Ajout d'options pour des versions recentes d'OpenMPI:
# --with-memory-manager=none evite les adress not mapped avec TRUST en share libs: important donc
options="--with-memory-manager=none --with-hwloc=internal --disable-libompitrace"
[ -f $TRUST_ROOT/exec/valgrind ] && options=$options" --with-valgrind=$TRUST_ROOT/exec/valgrind"
[ $version = $latest_version ] && options=$options" --enable-mpi1-compatibility" # HDF5 qui utilise des MPI deprecated...

# On disable diverses choses pour accelerer la compilation et reduire la taille de la libmpi.a 
# On retire  --disable-shared pour que les cas tests utilisant mpi4py tournent.
options="--enable-static --disable-mpi-cxx --enable-mca-no-build=maffinity-libnuma "$options
# Ajout CUDA:
[ "$TRUST_USE_CUDA" = 1 ] && options=$options" --with-cuda=$CUDA_INC_PATH"

# Telechargement du package
package=openmpi-$version.tar.gz
if [ ! -f $package ]
then
   rep_version=`echo $version | $TRUST_Awk -F. '{print $1"."$2}'`
   wget_ https://download.open-mpi.org/release/open-mpi/v$rep_version/$package
   if [ $? != 0 ] 
   then 
      wget_ http://download.open-mpi.org/release/open-mpi/v$rep_version/$package
      [ $? != 0 ] && exit -1
   fi
fi

echo "Using $package on $HOST..."
install=`pwd`/openmpi
install=$MPI_ROOT
src=${package%.tar.gz}
if [ ! -d $install ] || [ $package -nt $install ] || [ ! -d $src ]
then
   gunzip -c $package | tar -xf -
fi
cd $src

###############################
# Lancement de la configuration
###############################
export CXX=$TRUST_CC_BASE
export CC=$TRUST_cc_BASE
export F77=$TRUST_F77_BASE
export FC=$TRUST_F77_BASE
export CXXFLAGS="-fPIC -fno-strict-aliasing"
export CFLAGS="-fPIC -fno-strict-aliasing"
export FFLAGS="-fPIC -fno-strict-aliasing"
export FCFLAGS="-fPIC -fno-strict-aliasing"
[ `uname -s` != "Darwin" ] && export LDFLAGS="-Wl,--no-as-needed"
[ `uname -s` != "Darwin" ] && export LIBS="-ldl"
# Configuration:
./configure --help 2>&1 > ../configure.help
if [ "`grep f77 ../configure.help`" != "" ]
then
   # A partir d'OpenMPI 1.7, mpif77 et mpif90 -> mpifort
   options=$options" --with-wrapper-ldflags=-lmpi_f77"
fi
./configure --prefix=$install $options || exit -1

#############################
# Lancement de la compilation
#############################
$TRUST_MAKE || exit -1 

#######################
# Fin de l'installation
#######################
make install || exit -1
cd ..
rm -r -f $src configure.help

exit 0
