#!/bin/bash
mkdir -p Ny9 Ny17 Ny25 Ny25_02

cp ./*data Ny9
cp ./post_run Ny9
cp ./tableauFrott.awk Ny9

cp ./*data Ny17/.
cp ./post_run Ny17
cp ./tableauFrott.awk Ny17

cp ./*data Ny25/.
cp ./post_run Ny25
cp ./tableauFrott.awk Ny25

cd Ny17
sed "s/Nombre_de_Noeuds 3 9 3/Nombre_de_Noeuds 3 17 3/" canalVEF.data > toto.data
sed "s/Longueurs 0.5 2 0.5/Longueurs 0.25 2 0.25/" toto.data > canalVEF.data
sed "s/0. <= X <= 0.5/0. <= X <= 0.25/" canalVEF.data > toto.data
sed "s/0. <= Z <= 0.5/0. <= Z <= 0.25/" toto.data > canalVEF.data
sed "s/X = 0.5/X = 0.25/" canalVEF.data > toto.data
sed "s/Z = 0.5/Z = 0.25/" toto.data > canalVEF.data
sed "s/sonde_entre vitesse periode 100 segment 14/sonde_entre vitesse periode 100 segment 30/" canalVEF.data > toto.data
sed "s/sonde_mil vitesse periode 100 segment 14/sonde_mil vitesse periode 100 segment 30/" toto.data > canalVEF.data
rm toto.data
cd ..

cd Ny25
sed "s/Nombre_de_Noeuds 3 9 3/Nombre_de_Noeuds 3 25 3/" canalVEF.data > toto.data
sed "s/Longueurs 0.5 2 0.5/Longueurs 0.17 2 0.17/" toto.data > canalVEF.data
sed "s/0. <= X <= 0.5/0. <= X <= 0.17/" canalVEF.data > toto.data
sed "s/0. <= Z <= 0.5/0. <= Z <= 0.17/" toto.data > canalVEF.data
sed "s/X = 0.5/X = 0.17/" canalVEF.data > toto.data
sed "s/Z = 0.5/Z = 0.17/" toto.data > canalVEF.data
sed "s/sonde_entre vitesse periode 100 segment 14/sonde_entre vitesse periode 100 segment 50/" canalVEF.data > toto.data
sed "s/sonde_mil vitesse periode 100 segment 14/sonde_mil vitesse periode 100 segment 50/" toto.data > canalVEF.data
rm toto.data
cd ..

cp ./Ny25/*data Ny25_02/toto.data
cp ./post_run Ny25_02
cp ./tableauFrott.awk Ny25_02

cd Ny25_02
sed "s/{ EF_stab { } }/{ EF_stab { alpha 0.2 } }/" toto.data > canalVEF.data
rm toto.data
cd ..

sh ./first.awk canalVEF
