#!/bin/bash

if [ "`basename $PWD | grep vef_ef`" = ""  ] 
then
    echo on ne fait que 3 pas de temps
    sed "s/tinit/# que 3 pas pour la NR # nb_pas_dt_max 3 tinit/" EF.data > mod.data
    mv mod.data EF.data
fi

# Guess OPT from executable name.
OPT=""
list="_semi_opt _opt _opt_avx _opt_pg _custom _opt_gcov"
for option in $list; do 
   [ `echo $exec | grep $option$ 1>/dev/null 2>&1; echo $?` -eq 0  ] && OPT=$option && break
done
export OPT

make check
status=$?
exit $status
# GF cela ne va pas...
if [ $status -eq 0 ]
then
    cp EF.data  bidon.data
    echo resoudre pb >> bidon.data
    $exec bidon 1>bidon.out 2>bidon.err
    cp bidon.TU ref.TU
else
    rm -f ref.TU
fi
