#!/bin/bash

mkdir -p ../CHECKPOINT_FILES

if [ -f sauvegarde.dt_ev ]
then
    cp sauvegarde_Channel_Flow_Rate_repr_pb_periox ../CHECKPOINT_FILES/reprise_Channel_Flow_Rate_repr_pb_periox
    cp canal.sauv ../CHECKPOINT_FILES
fi

if [ "$TRUST_DISABLE_MPI" != 1 ] && [ -f PAR_sauvegarde.dt_ev ]
then
    cp PAR_sauvegarde_Channel_Flow_Rate_repr_pb_periox ../CHECKPOINT_FILES/PAR_reprise_Channel_Flow_Rate_repr_pb_periox
    cp PAR_canal.sauv ../CHECKPOINT_FILES
fi
