#!/bin/bash

#full computation for reference
mkdir -p CHECKPOINT_RESTART/REF; cd CHECKPOINT_RESTART/REF
cp ../../sauvegarde_reprise.data ref.data
sed -i "s/tinit.*/tinit 0.0/g" ref.data
sed -i "s/tmax.*/tmax 0.12/g" ref.data
sed -i '/$checkpoint_restart /d' ref.data

trust ref.data 1>/dev/null 2>&1 || exit -1
