#!/bin/bash

# Conversion of .plan files to .lata files
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PX1Z TwoDimRepresentation -lp
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PX1Z.plan Canal_SONDE_PX1Z -l
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PXY1 Canal_SONDE_PXY1.lata -l
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_VXY0 -l
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PINCLINED -l
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PXYZ -l
python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_V4YZ -l


# Projection that will crash since the plan defining SONDE_PINCLINED is inclined ! 
# python $TRUST_ROOT/Outils/lata2dx/lata2dx/Plan_to_lata.py Canal_SONDE_PINCLINED.plan toto.lata -lp
