#!/bin/bash

# Conversion of .plan files to .lata files
python $TRUST_ROOT/Outils/lata_tools/src/scripts/Plan_to_lata.py Obstacle_P_PROBE.plan -l
python $TRUST_ROOT/Outils/lata_tools/src/scripts/Plan_to_lata.py Obstacle_V_PROBE.plan toto_obstacle.lata -l



