#!/bin/bash

# On teste lata_analyzer ... 
# write_singlelata + faces fields
lata_analyzer Extruder_en3_single_lata.lata writelata=split.lata export_fields_at_faces 1>lata_analyzer1.log 2>&1 || exit -1
compare_lata_gz Extruder_en3_single_lata.lata split.lata 1>verifie1.log 2>&1 || exit -1

numb_diff1=`awk '$1=="Number"{print $5}' verifie1.log`
if [[ "$numb_diff1" -gt "0" ]]
then
  echo "   ===> Error in compare_lata !"
  exit -1
else
  echo "   ===> All OK in compare_lata : single vs multiple files from lata_analyzer !"
fi

# writelata .. to split the single
lata_analyzer split.lata write_singlelata=single.lata export_fields_at_faces 1>lata_analyzer2.log 2>&1 || exit -1
compare_lata_gz split.lata single.lata 1>verifie2.log 2>&1 || exit -1

numb_diff2=`awk '$1=="Number"{print $5}' verifie2.log`
if [[ "$numb_diff2" -gt "0" ]]
then
  echo "   ===> Error in compare_lata !"
  exit -1
else
  echo "   ===> All OK in compare_lata : single vs multiple files from lata_analyzer !"
fi

# further
compare_lata_gz Extruder_en3_single_lata.lata single.lata 1>verifie3.log 2>&1 || exit -1

numb_diff3=`awk '$1=="Number"{print $5}' verifie3.log`
if [[ "$numb_diff3" -gt "0" ]]
then
  echo "   ===> Error in compare_lata !"
  exit -1
else
  echo "   ===> All OK in compare_lata : single vs single files from lata_analyzer !"
fi