#!/bin/bash

resp=`tail -1 cas_ERRP.son | awk '{print $2}'`
nup=`grep "Total number of elements" $1.err | awk '{print $6}'`
echo $resp $nup > conv_p

resv=`tail -1 cas_ERRV.son | awk '{print $2}'`
nuu=`grep "Total number of faces" $1.err | awk '{print $6}'`
echo $resv $nuu > conv_v