/****************************************************************************
* Copyright (c) 2015, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
//////////////////////////////////////////////////////////////////////////////
//
// File:        Op_Conv_EF.cpp
// Directory:   $TRUST_ROOT/src/EF/Operateurs
// Version:     /main/23
//
//////////////////////////////////////////////////////////////////////////////
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file Op_Conv_EF.cpp.P
//

#include <Op_Conv_EF.h>
#include <Debog.h>
#include <Schema_Temps_base.h>
#include <Probleme_base.h>
#include <Param.h>

#include <Op_Diff_EF.h>

Implemente_instanciable_sans_constructeur(Op_Conv_EF,"Op_Conv_Generic_EF",Op_Conv_EF_base);

Op_Conv_EF::Op_Conv_EF(): hourglass(0.),hourglass_impl_(0),btd_impl_(0),centre_impl_(0), hourglass_hors_conv_(0),btd_hors_conv_(0),f_lu_(-1.),calcul_dt_stab_(0)
{
}

Implemente_instanciable_sans_constructeur(Op_Conv_BTD_EF,"Op_Conv_BTD_EF",Op_Conv_EF);
Op_Conv_BTD_EF::Op_Conv_BTD_EF() : Op_Conv_EF()
{
  calcul_dt_stab_=2;
  type_op = amont;
  hourglass=1;
  hourglass_impl_=1;
  btd_impl_=1;
  centre_impl_=1;
  btd_hors_conv_=1;
  hourglass_hors_conv_=1;
}
void Op_Conv_BTD_EF::completer()
{
  // pour ne pas mettre les flags automatiquement
  Op_Conv_EF_base::completer();

}
Sortie& Op_Conv_BTD_EF::printOn(Sortie& s ) const
{
  return s << que_suis_je() ;
}
Entree& Op_Conv_BTD_EF::readOn(Entree& s )
{
  Param param(que_suis_je()); // XD convection_btd convection_deriv btd 1 not_set
  param.ajouter("btd",&btd_,Param::REQUIRED); // XD_ADD_P double not_set
  param.ajouter("facteur",&facteur_,Param::REQUIRED);  // XD_ADD_P double not_set

  param.lire_avec_accolades(s);
  return s;
}

double Op_Conv_BTD_EF::coefficient_btd() const
{
  if (equation().equation_non_resolue())
    calculer_dt_stab();
  double f=dt_stab_conv()*facteur_*btd_/2.;
// Cerr<<"ici btd " <<f<<finl;
  return f;
}
//// printOn
//
Sortie& Op_Conv_EF::printOn(Sortie& s ) const
{
  return s << que_suis_je() ;
}

//// readOn
//
Entree& Op_Conv_EF::readOn(Entree& s )
{
  btd_=3.;
  Motcle type_op_lu;
  s >> type_op_lu;

  if (!(type_op_lu=="amont") &&  !(type_op_lu=="centre")  &&  !(type_op_lu=="amont3")&&!(type_op_lu=="btd"))
    {
      Cerr << type_op_lu << " n'est pas compris par " << que_suis_je() << finl;
      Cerr << " choisir parmi : amont -btd - centre " << finl;
      exit();
    }


  if (type_op_lu=="centre")
    {
      type_op = centre;

    }

  if ((type_op_lu=="amont")||(type_op_lu=="amont3")||(type_op_lu=="btd"))
    {
      type_op = amont;
    }


  if ((type_op==amont)
      and  (type_op_lu!="amont2"))
    {
      f_lu_=0.036585;
      hourglass=1;
      hourglass_impl_=1;
      btd_impl_=1;
      centre_impl_=1;
    }
  if (type_op_lu=="amont3")
    {
      s >> f_lu_;
      // decommente  les 2 lognes
      // centre_impl_=0;
      //	calcul_dt_stab_=1;
    }
  if  (type_op_lu=="btd")
    f_lu_=-1;


  return s ;
}
void Op_Conv_EF::completer()
{
  Op_Conv_EF_base::completer();
  if (sub_type(Op_Diff_EF,equation().operateur(0).l_op_base()))
    {
      if (equation().schema_temps().diffusion_implicite())
        {
          btd_hors_conv_=1;
          hourglass_hors_conv_=1;
          calcul_dt_stab_=2;
        }
    }
  else
    {
      btd_hors_conv_=0;
      hourglass_hors_conv_=0;
    }

}
//
//   Fonctions de la classe Op_Conv_EF
//
////////////////////////////////////////////////////////////////////
//
//                      Implementation des fonctions
//
//                   de la classe Op_Conv_EF
//
////////////////////////////////////////////////////////////////////



DoubleTab& Op_Conv_EF::ajouter(const DoubleTab& transporte,
                               DoubleTab& resu) const
{
  return ajouter_sous_cond(transporte,resu,btd_hors_conv_,hourglass_hors_conv_,0);
}
DoubleTab& Op_Conv_EF::ajouter_a_la_diffusion(const DoubleTab& transporte,
                                              DoubleTab& resu) const
{
  return ajouter_sous_cond(transporte,resu,!btd_hors_conv_,!hourglass_hors_conv_,1);
}


double Op_Conv_EF::coefficient_btd() const
{
  double dt=equation().schema_temps().pas_de_temps();
  double f=(dimension)*dt/(dimension-1);
  if (f_lu_>=0) f=f_lu_;
  return f;
}


// macro declare_ajouter(dimension,nbdim,nb_comp,nb_som_elem,dim_fois_nbn,gen)


DoubleTab& Op_Conv_EF::ajouter_sous_cond_gen(const DoubleTab& transporte,
                                             DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_dim=resu.nb_dim();
  const int nb_som_elem=zone_ef.zone().nb_som_elem();



    if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;

    DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);

    /*
    assert((type_op==amont) || (type_op==muscl) || (type_op==centre));
    const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
    const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
    */
    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);
    Debog::verifier("conv vitesse",G);
    Debog::verifier("conv rho",rho_elem);
    Debog::verifier("conv transporte",transporte);
    int nb_comp0 = 1;
//int nb_dim = resu.nb_dim();
    //const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp0=resu.dimension(1);

      }

    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();

    const IntTab& elems=zone_ef.zone().les_elems() ;

    double f= coefficient_btd();

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};

    DoubleTab transp_loc(nb_som_elem,nb_comp0);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //Cout<<dt<<" BTD "<<f<<finl;
    //



    const int nb_comp=nb_comp0;
    const int const_dimension=Objet_U::dimension;
    //int nb_som_elem=zone_ef.zone().nb_som_elem();
    ArrOfDouble G_e(const_dimension);
    ArrOfDouble pr(nb_comp),ge_bij(nb_som_elem);

#define bij_(elem,i,j) bij(elem,i,j)
#define transp_loc_(som,a) transp_loc(som,a)

#define transporte_(som,a) transporte(som,a)
#define resu_(som,a) resu(som,a)





    double inv_nb_som_elem=1./nb_som_elem;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<const_dimension; b++)
                G_e[b]+=G(glob,b);
              if (nb_dim==1)
                transp_loc(i1,0)=transporte(glob);
              else
                for (int a=0; a<nb_comp; a++)
                  transp_loc(i1,a)=transporte_(glob,a);
            }
          G_e*=inv_nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double vol_elem=volumes(elem);
          double inv_vol_elem=1./vol_elem;
          double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;


          if (transport_rhou) pond2/=rho_elem(elem);
          double fpond2=f*pond2;

          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                     +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));

                  double t3d=0;
                  for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                  t3d*=coef3d;
                  double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                      -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                  if (!est_egal(t3d,t3db,1e-6))
                    {
                      assert(0);
                    }
                  /*
                  double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                  double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                  double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                  double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                  */
                  //	  if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                  if (nb_dim==1)
                    {
                      for (int i=0; i<8; i++)
                        resu(elems(elem,i))-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));


                      /* {
                         resu(elems(elem,0))-=t3d+t1;
                         resu(elems(elem,1))-=-t3d+t2;
                         resu(elems(elem,2))-=-t3d+t4;
                         resu(elems(elem,3))-=t3d+t3;
                         resu(elems(elem,4))-=-t3d+t3;
                         resu(elems(elem,5))-=t3d+t4;
                         resu(elems(elem,6))-=t3d+t2;
                         resu(elems(elem,7))-=-t3d+t1;
                      }*/
                    }
                  else
                    {
                      for (int i=0; i<8; i++)
                        resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
                    }
                }

            }



          {

            for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
            if ((centre_impl==0)||(btd_impl==0))
              {
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double cb=0;
                    for (int b=0; b<const_dimension; b++)
                      cb+=G_e[b]*bij_(elem,i1,b);
                    ge_bij[i1]=cb;
                  }
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double pond=0;
                    if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                    int glob=elems(elem,i1);
                    //pr=0;
                    for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;

                    double cbbtd=pond;
                    if ((btd_impl==0)&&(type_op==amont))
                      cbbtd+=ge_bij[i1]*(fpond2);
                    for (int i2=0; i2<nb_som_elem; i2++)
                      {
                        const double cbi2=ge_bij[i2];
                        double coef=cbbtd*cbi2;
                        for (int a=0; a<nb_comp; a++)
                          pr[a]-=coef*transp_loc_(i2,a);
                      }
                    if (nb_dim==1)
                      resu(glob)+=pr[0];
                    else
                      for (int a=0; a<nb_comp; a++)
                        resu_(glob,a)+=pr[a];
                  }
              }

          }
        }



    fluent_.echange_espace_virtuel();
    return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
  }


  DoubleTab& Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(const DoubleTab& transporte,
                                                                                               DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
  {
    const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
    const int nb_som_elem=8;
    const int nb_dim=2;


    if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;

    DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);

    /*
    assert((type_op==amont) || (type_op==muscl) || (type_op==centre));
    const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
    const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
    */
    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);
    Debog::verifier("conv vitesse",G);
    Debog::verifier("conv rho",rho_elem);
    Debog::verifier("conv transporte",transporte);
    int nb_comp0 = 1;
//int nb_dim = resu.nb_dim();
    //const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp0=resu.dimension(1);

      }

    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();

    const IntTab& elems=zone_ef.zone().les_elems() ;

    double f= coefficient_btd();

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};

    DoubleTab transp_loc(nb_som_elem,nb_comp0);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //Cout<<dt<<" BTD "<<f<<finl;
    //



    const int const_dimension= 3;
    //const int nb_som_elem= 8;
    const int nb_comp=3;
    const int dim_fois_nbn=24;
    if (nb_comp0!=nb_comp) abort();

    ArrOfDouble G_e(const_dimension);
    double pr[nb_comp],ge_bij[nb_som_elem];
    const double* bij_ptr=bij.addr();
    const double* transp_loc_ptr=transp_loc.addr();
    const double* transporte_ptr=transporte.addr();
    double* resu_ptr=resu.addr();

#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]

#define resu_(som,a) resu_ptr[som*nb_comp+a]



    double inv_nb_som_elem=1./nb_som_elem;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<const_dimension; b++)
                G_e[b]+=G(glob,b);
              if (nb_dim==1)
                transp_loc(i1,0)=transporte(glob);
              else
                for (int a=0; a<nb_comp; a++)
                  transp_loc(i1,a)=transporte_(glob,a);
            }
          G_e*=inv_nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double vol_elem=volumes(elem);
          double inv_vol_elem=1./vol_elem;
          double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;


          if (transport_rhou) pond2/=rho_elem(elem);
          double fpond2=f*pond2;

          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                     +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));

                  double t3d=0;
                  for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                  t3d*=coef3d;
                  double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                      -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                  if (!est_egal(t3d,t3db,1e-6))
                    {
                      assert(0);
                    }
                  /*
                  double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                  double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                  double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                  double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                  */
                  //	  if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                  if (nb_dim==1)
                    {
                      for (int i=0; i<8; i++)
                        resu(elems(elem,i))-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));


                      /* {
                         resu(elems(elem,0))-=t3d+t1;
                         resu(elems(elem,1))-=-t3d+t2;
                         resu(elems(elem,2))-=-t3d+t4;
                         resu(elems(elem,3))-=t3d+t3;
                         resu(elems(elem,4))-=-t3d+t3;
                         resu(elems(elem,5))-=t3d+t4;
                         resu(elems(elem,6))-=t3d+t2;
                         resu(elems(elem,7))-=-t3d+t1;
                      }*/
                    }
                  else
                    {
                      for (int i=0; i<8; i++)
                        resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
                    }
                }

            }



          {

            for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
            if ((centre_impl==0)||(btd_impl==0))
              {
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double cb=0;
                    for (int b=0; b<const_dimension; b++)
                      cb+=G_e[b]*bij_(elem,i1,b);
                    ge_bij[i1]=cb;
                  }
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double pond=0;
                    if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                    int glob=elems(elem,i1);
                    //pr=0;
                    for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;

                    double cbbtd=pond;
                    if ((btd_impl==0)&&(type_op==amont))
                      cbbtd+=ge_bij[i1]*(fpond2);
                    for (int i2=0; i2<nb_som_elem; i2++)
                      {
                        const double cbi2=ge_bij[i2];
                        double coef=cbbtd*cbi2;
                        for (int a=0; a<nb_comp; a++)
                          pr[a]-=coef*transp_loc_(i2,a);
                      }
                    if (nb_dim==1)
                      resu(glob)+=pr[0];
                    else
                      for (int a=0; a<nb_comp; a++)
                        resu_(glob,a)+=pr[a];
                  }
              }

          }
        }



    fluent_.echange_espace_virtuel();
    return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
  }

  DoubleTab& Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(const DoubleTab& transporte,
                                                                                               DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
  {
    const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
    const int nb_som_elem=8;
    const int nb_dim=1;


    if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;

    DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);

    /*
    assert((type_op==amont) || (type_op==muscl) || (type_op==centre));
    const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
    const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
    */
    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);
    Debog::verifier("conv vitesse",G);
    Debog::verifier("conv rho",rho_elem);
    Debog::verifier("conv transporte",transporte);
    int nb_comp0 = 1;
//int nb_dim = resu.nb_dim();
    //const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp0=resu.dimension(1);

      }

    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();

    const IntTab& elems=zone_ef.zone().les_elems() ;

    double f= coefficient_btd();

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};

    DoubleTab transp_loc(nb_som_elem,nb_comp0);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //Cout<<dt<<" BTD "<<f<<finl;
    //



    const int const_dimension= 3;
    //const int nb_som_elem= 8;
    const int nb_comp=1;
    const int dim_fois_nbn=24;
    if (nb_comp0!=nb_comp) abort();

    ArrOfDouble G_e(const_dimension);
    double pr[nb_comp],ge_bij[nb_som_elem];
    const double* bij_ptr=bij.addr();
    const double* transp_loc_ptr=transp_loc.addr();
    const double* transporte_ptr=transporte.addr();
    double* resu_ptr=resu.addr();

#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]

#define resu_(som,a) resu_ptr[som*nb_comp+a]



    double inv_nb_som_elem=1./nb_som_elem;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<const_dimension; b++)
                G_e[b]+=G(glob,b);
              if (nb_dim==1)
                transp_loc(i1,0)=transporte(glob);
              else
                for (int a=0; a<nb_comp; a++)
                  transp_loc(i1,a)=transporte_(glob,a);
            }
          G_e*=inv_nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double vol_elem=volumes(elem);
          double inv_vol_elem=1./vol_elem;
          double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;


          if (transport_rhou) pond2/=rho_elem(elem);
          double fpond2=f*pond2;

          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                     +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));

                  double t3d=0;
                  for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                  t3d*=coef3d;
                  double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                      -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                  if (!est_egal(t3d,t3db,1e-6))
                    {
                      assert(0);
                    }
                  /*
                  double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                  double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                  double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                  double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                  */
                  //	  if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                  if (nb_dim==1)
                    {
                      for (int i=0; i<8; i++)
                        resu(elems(elem,i))-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));


                      /* {
                         resu(elems(elem,0))-=t3d+t1;
                         resu(elems(elem,1))-=-t3d+t2;
                         resu(elems(elem,2))-=-t3d+t4;
                         resu(elems(elem,3))-=t3d+t3;
                         resu(elems(elem,4))-=-t3d+t3;
                         resu(elems(elem,5))-=t3d+t4;
                         resu(elems(elem,6))-=t3d+t2;
                         resu(elems(elem,7))-=-t3d+t1;
                      }*/
                    }
                  else
                    {
                      for (int i=0; i<8; i++)
                        resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
                    }
                }

            }



          {

            for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
            if ((centre_impl==0)||(btd_impl==0))
              {
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double cb=0;
                    for (int b=0; b<const_dimension; b++)
                      cb+=G_e[b]*bij_(elem,i1,b);
                    ge_bij[i1]=cb;
                  }
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double pond=0;
                    if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                    int glob=elems(elem,i1);
                    //pr=0;
                    for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;

                    double cbbtd=pond;
                    if ((btd_impl==0)&&(type_op==amont))
                      cbbtd+=ge_bij[i1]*(fpond2);
                    for (int i2=0; i2<nb_som_elem; i2++)
                      {
                        const double cbi2=ge_bij[i2];
                        double coef=cbbtd*cbi2;
                        for (int a=0; a<nb_comp; a++)
                          pr[a]-=coef*transp_loc_(i2,a);
                      }
                    if (nb_dim==1)
                      resu(glob)+=pr[0];
                    else
                      for (int a=0; a<nb_comp; a++)
                        resu_(glob,a)+=pr[a];
                  }
              }

          }
        }



    fluent_.echange_espace_virtuel();
    return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
  }


  DoubleTab& Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(const DoubleTab& transporte,
                                                                                               DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
  {
    const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
    const int nb_som_elem=4;
    const int nb_dim=2;


    if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;

    DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);

    /*
    assert((type_op==amont) || (type_op==muscl) || (type_op==centre));
    const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
    const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
    */
    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);
    Debog::verifier("conv vitesse",G);
    Debog::verifier("conv rho",rho_elem);
    Debog::verifier("conv transporte",transporte);
    int nb_comp0 = 1;
//int nb_dim = resu.nb_dim();
    //const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp0=resu.dimension(1);

      }

    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();

    const IntTab& elems=zone_ef.zone().les_elems() ;

    double f= coefficient_btd();

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};

    DoubleTab transp_loc(nb_som_elem,nb_comp0);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //Cout<<dt<<" BTD "<<f<<finl;
    //



    const int const_dimension= 2;
    //const int nb_som_elem= 4;
    const int nb_comp=2;
    const int dim_fois_nbn=8;
    if (nb_comp0!=nb_comp) abort();

    ArrOfDouble G_e(const_dimension);
    double pr[nb_comp],ge_bij[nb_som_elem];
    const double* bij_ptr=bij.addr();
    const double* transp_loc_ptr=transp_loc.addr();
    const double* transporte_ptr=transporte.addr();
    double* resu_ptr=resu.addr();

#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]

#define resu_(som,a) resu_ptr[som*nb_comp+a]



    double inv_nb_som_elem=1./nb_som_elem;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<const_dimension; b++)
                G_e[b]+=G(glob,b);
              if (nb_dim==1)
                transp_loc(i1,0)=transporte(glob);
              else
                for (int a=0; a<nb_comp; a++)
                  transp_loc(i1,a)=transporte_(glob,a);
            }
          G_e*=inv_nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double vol_elem=volumes(elem);
          double inv_vol_elem=1./vol_elem;
          double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;


          if (transport_rhou) pond2/=rho_elem(elem);
          double fpond2=f*pond2;

          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                     +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));

                  double t3d=0;
                  for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                  t3d*=coef3d;
                  double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                      -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                  if (!est_egal(t3d,t3db,1e-6))
                    {
                      assert(0);
                    }
                  /*
                  double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                  double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                  double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                  double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                  */
                  //	  if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                  if (nb_dim==1)
                    {
                      for (int i=0; i<8; i++)
                        resu(elems(elem,i))-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));


                      /* {
                         resu(elems(elem,0))-=t3d+t1;
                         resu(elems(elem,1))-=-t3d+t2;
                         resu(elems(elem,2))-=-t3d+t4;
                         resu(elems(elem,3))-=t3d+t3;
                         resu(elems(elem,4))-=-t3d+t3;
                         resu(elems(elem,5))-=t3d+t4;
                         resu(elems(elem,6))-=t3d+t2;
                         resu(elems(elem,7))-=-t3d+t1;
                      }*/
                    }
                  else
                    {
                      for (int i=0; i<8; i++)
                        resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
                    }
                }

            }



          {

            for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
            if ((centre_impl==0)||(btd_impl==0))
              {
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double cb=0;
                    for (int b=0; b<const_dimension; b++)
                      cb+=G_e[b]*bij_(elem,i1,b);
                    ge_bij[i1]=cb;
                  }
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double pond=0;
                    if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                    int glob=elems(elem,i1);
                    //pr=0;
                    for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;

                    double cbbtd=pond;
                    if ((btd_impl==0)&&(type_op==amont))
                      cbbtd+=ge_bij[i1]*(fpond2);
                    for (int i2=0; i2<nb_som_elem; i2++)
                      {
                        const double cbi2=ge_bij[i2];
                        double coef=cbbtd*cbi2;
                        for (int a=0; a<nb_comp; a++)
                          pr[a]-=coef*transp_loc_(i2,a);
                      }
                    if (nb_dim==1)
                      resu(glob)+=pr[0];
                    else
                      for (int a=0; a<nb_comp; a++)
                        resu_(glob,a)+=pr[a];
                  }
              }

          }
        }



    fluent_.echange_espace_virtuel();
    return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
  }

  DoubleTab& Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(const DoubleTab& transporte,
                                                                                               DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
  {
    const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
    const int nb_som_elem=4;
    const int nb_dim=1;


    if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;

    DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);

    /*
    assert((type_op==amont) || (type_op==muscl) || (type_op==centre));
    const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
    const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
    */
    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);
    Debog::verifier("conv vitesse",G);
    Debog::verifier("conv rho",rho_elem);
    Debog::verifier("conv transporte",transporte);
    int nb_comp0 = 1;
//int nb_dim = resu.nb_dim();
    //const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp0=resu.dimension(1);

      }

    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();

    const IntTab& elems=zone_ef.zone().les_elems() ;

    double f= coefficient_btd();

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};

    DoubleTab transp_loc(nb_som_elem,nb_comp0);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //Cout<<dt<<" BTD "<<f<<finl;
    //



    const int const_dimension= 2;
    //const int nb_som_elem= 4;
    const int nb_comp=1;
    const int dim_fois_nbn=8;
    if (nb_comp0!=nb_comp) abort();

    ArrOfDouble G_e(const_dimension);
    double pr[nb_comp],ge_bij[nb_som_elem];
    const double* bij_ptr=bij.addr();
    const double* transp_loc_ptr=transp_loc.addr();
    const double* transporte_ptr=transporte.addr();
    double* resu_ptr=resu.addr();

#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]

#define resu_(som,a) resu_ptr[som*nb_comp+a]



    double inv_nb_som_elem=1./nb_som_elem;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<const_dimension; b++)
                G_e[b]+=G(glob,b);
              if (nb_dim==1)
                transp_loc(i1,0)=transporte(glob);
              else
                for (int a=0; a<nb_comp; a++)
                  transp_loc(i1,a)=transporte_(glob,a);
            }
          G_e*=inv_nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double vol_elem=volumes(elem);
          double inv_vol_elem=1./vol_elem;
          double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;


          if (transport_rhou) pond2/=rho_elem(elem);
          double fpond2=f*pond2;

          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                     +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));

                  double t3d=0;
                  for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                  t3d*=coef3d;
                  double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                      -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                  if (!est_egal(t3d,t3db,1e-6))
                    {
                      assert(0);
                    }
                  /*
                  double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                  double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                  double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                  double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                  */
                  //	  if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                  if (nb_dim==1)
                    {
                      for (int i=0; i<8; i++)
                        resu(elems(elem,i))-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));


                      /* {
                         resu(elems(elem,0))-=t3d+t1;
                         resu(elems(elem,1))-=-t3d+t2;
                         resu(elems(elem,2))-=-t3d+t4;
                         resu(elems(elem,3))-=t3d+t3;
                         resu(elems(elem,4))-=-t3d+t3;
                         resu(elems(elem,5))-=t3d+t4;
                         resu(elems(elem,6))-=t3d+t2;
                         resu(elems(elem,7))-=-t3d+t1;
                      }*/
                    }
                  else
                    {
                      for (int i=0; i<8; i++)
                        resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
                    }
                }

            }



          {

            for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
            if ((centre_impl==0)||(btd_impl==0))
              {
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double cb=0;
                    for (int b=0; b<const_dimension; b++)
                      cb+=G_e[b]*bij_(elem,i1,b);
                    ge_bij[i1]=cb;
                  }
                for (int i1=0; i1<nb_som_elem; i1++)
                  {
                    double pond=0;
                    if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                    int glob=elems(elem,i1);
                    //pr=0;
                    for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;

                    double cbbtd=pond;
                    if ((btd_impl==0)&&(type_op==amont))
                      cbbtd+=ge_bij[i1]*(fpond2);
                    for (int i2=0; i2<nb_som_elem; i2++)
                      {
                        const double cbi2=ge_bij[i2];
                        double coef=cbbtd*cbi2;
                        for (int a=0; a<nb_comp; a++)
                          pr[a]-=coef*transp_loc_(i2,a);
                      }
                    if (nb_dim==1)
                      resu(glob)+=pr[0];
                    else
                      for (int a=0; a<nb_comp; a++)
                        resu_(glob,a)+=pr[a];
                  }
              }

          }
        }



    fluent_.echange_espace_virtuel();
    return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
  }




  DoubleTab& Op_Conv_EF::ajouter_sous_cond(const DoubleTab& transporte,
                                           DoubleTab& resu,int btd_impl,int hourglass_impl,int centre_impl) const
  {
    const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    int nb_som_elem=zone_ef.zone().nb_som_elem();
    int nb_dim=transporte.nb_dim();

    if ((dimension==3)&&(nb_som_elem==8))
      {
        if (nb_dim==1)
          return ajouter_sous_cond_dim3_nbn8_nbdim1(transporte,resu,btd_impl,hourglass_impl,centre_impl);
        else
          return ajouter_sous_cond_dim3_nbn8_nbdim2(transporte,resu,btd_impl,hourglass_impl,centre_impl);
      }
    return ajouter_sous_cond_gen(transporte,resu,btd_impl,hourglass_impl,centre_impl);
  }

  void Op_Conv_EF::ajouter_contribution_sous_cond(const DoubleTab& transporte, Matrice_Morse& matrice,int btd_impl,int hourglass_impl,int centre_impl ) const
  {

    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);

    int nb_comp = 1;
    int nb_dim = transporte.nb_dim();
    const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    if(nb_dim==2)
      {
        nb_comp=transporte.dimension(1);
      }
    const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
    const DoubleVect& volumes= zone_ef.volumes();
    const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();

    const DoubleTab& bij=zone_ef.Bij();
    int nb_elem_tot=zone_ef.zone().nb_elem_tot();
    int nb_som_elem=zone_ef.zone().nb_som_elem();
    const IntTab& elems=zone_ef.zone().les_elems() ;
    ArrOfDouble G_e(dimension);

    double f=coefficient_btd();
    //  DoubleTab transp_loc(nb_som_elem,nb_comp);
    // A DEPLACER !!!!!
    const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
    int is_not_lambda_unif=1;
    if (lambda.size()==1)
      {
        is_not_lambda_unif=0;
      }
    //  Cout<<dt<<" BTD "<<f<<finl;

    int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
    int sommetoppose[8]= {7,6,5,4,3,2,1,0};
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<dimension; b++)
                G_e(b)+=G(glob,b);
            }
          G_e/=nb_som_elem;
          // Cerr<<" coucou "<<G_e<<finl;
          // *10 !!!!!!!!!!!
          double pond2=volumes_thilde(elem)/volumes(elem)/volumes(elem);


          if (transport_rhou) pond2/=rho_elem(elem);


          if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==1))
            {
              double pond3=f*dotproduct_array(G_e,G_e);
              if (transport_rhou) pond3/=rho_elem(elem);
              if (is_not_lambda_unif)
                pond3+=lambda(elem);
              else
                pond3+=lambda(0,0);
              pond3*=volumes_thilde(elem)/volumes(elem)*pow(volumes(elem),0.3333333333333333);
              pond3*=hourglass;

              for (int a=0; a<nb_comp; a++)
                {


                  double coef2d=0.042*pond3;
                  double coef3d=coef2d*0.5;

                  for (int i1=0; i1<8; i1++)
                    {
                      int n1=elems(elem,i1)*nb_comp+a;
                      for (int i2=0; i2<8; i2++)
                        {
                          int n2=elems(elem,i2)*nb_comp+a;
                          matrice.coef(n1,n2)+=mcoef3d[i1]*mcoef3d[i2]*coef3d-coef2d;
                        }
                      matrice.coef(n1,n1)+=coef2d*4.;
                      matrice.coef(n1,elems(elem,sommetoppose[i1])*nb_comp+a)+=coef2d*4.;
                    }
                }

            }

          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);

              if (((btd_impl==1)&&(type_op==amont))||(centre_impl==1))
                {
                  double cb=0;
                  for (int b=0; b<dimension; b++)
                    cb+=G_e(b)*bij(elem,i1,b);
                  cb*=(f*pond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      int glob2=elems(elem,i2);

                      double ca=0;
                      if (centre_impl==1)
                        {
                          for (int b=0; b<dimension; b++)
                            ca+=G_e(b)*bij(elem,i2,b);
                          double pond=IPhi_thilde(elem,i1)/volumes(elem);

                          ca*=pond;
                        }
                      double cc=0;
                      if ((btd_impl==1)&&(type_op==amont))
                        {
                          for (int c=0; c<dimension; c++)
                            cc+=G_e(c)*bij(elem,i2,c);
                          cc*=cb;
                        }
                      //resu(glob)-=cc*cb*transp_loc(i2,0);
                      for (int a=0; a<nb_comp; a++)
                        {
                          int n1=glob*nb_comp+a;
                          int n2=glob2*nb_comp+a;
                          matrice.coef(n1,n2)+=cc+ca;

                        }

                    }
                }
            }
        }
    return;
  }
  void Op_Conv_EF::ajouter_contribution(const DoubleTab& transporte, Matrice_Morse& matrice ) const
  {
    return ajouter_contribution_sous_cond(transporte,matrice,(btd_impl_)&&(btd_hors_conv_==0),(hourglass_impl_)&&(hourglass_hors_conv_==0),centre_impl_);
  }

  void Op_Conv_EF::ajouter_contribution_a_la_diffusion(const DoubleTab& transporte, Matrice_Morse& matrice ) const
  {
    // return;
    ajouter_contribution_sous_cond(transporte,matrice,(btd_impl_)&&(btd_hors_conv_==1),(hourglass_impl_)&&(hourglass_hors_conv_==1),0);

  }



  double Op_Conv_EF::calculer_dt_stab() const
  {
    if (calcul_dt_stab_==0)
      return  Operateur_base::calculer_dt_stab();

    const Champ_Inc_base& la_vitesse=vitesse_.valeur();
    const DoubleTab& G=la_vitesse.valeurs();

    int transport_rhou=0;
    if (vitesse_.le_nom()=="rho_u")
      {
        transport_rhou=1;
      }
    // else abort();
    const DoubleTab& rho_elem=(transport_rhou==1?equation().probleme().get_champ("masse_volumique_melange").valeurs():G);


    const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
    const DoubleVect&      valeurs_diffusivite = ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();

    int autre_eq=0;
    const DoubleVect&      valeurs_diffusivite_p = ref_cast(Operateur_Diff_base,equation().probleme().equation(autre_eq).operateur(0).l_op_base()).diffusivite().valeurs();
    if (calcul_dt_stab_==2)
      {

        if (&valeurs_diffusivite_p==& valeurs_diffusivite)
          autre_eq=1;
      }
    const DoubleVect&      valeurs_diffusivite_2 = ref_cast(Operateur_Diff_base,equation().probleme().equation(autre_eq).operateur(0).l_op_base()).diffusivite().valeurs();

    const DoubleTab& coord=zone_ef.zone().domaine().les_sommets();

    int nb_elem_tot=zone_ef.zone().nb_elem_tot();
    int nb_som_elem=zone_ef.zone().nb_som_elem();
    const IntTab& elems=zone_ef.zone().les_elems() ;
    ArrOfDouble G_e(dimension);
    max_ue_=1e-8 ; // comme G2
    min_dx_=1e37;
    double Max=0;
    double dt_l=0,dt2=0;
    for (int elem=0; elem<nb_elem_tot; elem++)
      if (elem_contribue(elem))
        {
          G_e=0;
          for (int i1=0; i1<nb_som_elem; i1++)
            {
              int glob=elems(elem,i1);
              for (int b=0; b<dimension; b++)
                G_e(b)+=G(glob,b);
            }
          G_e/=nb_som_elem;
          //if (transport_rhou) 	G_e/=rho_elem(elem);
          double ml=0;
          double dx2;
          // pas de temps de diffusion !!
          double ml2=0;
          double vx[3];
          for (int d=0; d<3; d++)
            {
              dx2=dabs(coord(elems(elem,0),d)-coord(elems(elem,7),d));
              dx2+=dabs(coord(elems(elem,1),d)-coord(elems(elem,6),d));
              dx2+=dabs(coord(elems(elem,2),d)-coord(elems(elem,5),d));
              dx2+=dabs(coord(elems(elem,3),d)-coord(elems(elem,4),d));
              dx2*=0.25;
              //  if (dx2<1e-3) Cerr<<"iiiiiii " << dx2<<finl;
              dx2*=dx2;

              ml2+=dx2;
              //double p=G_e(d)*G_e(d)/dx2;
              // Cerr<<"ici "<<d <<" "<< p<<" "<<G_e(d)*G_e(d)<<" "<<dx2<<finl;
              ml+=G_e(d)*G_e(d)/dx2;
              vx[d]=G_e(d)*G_e(d);
            }

          double diffu=valeurs_diffusivite(elem);
          if (calcul_dt_stab_==2)
            {
              double diffu2=valeurs_diffusivite_2(elem);
              if (diffu2<diffu)
                diffu=diffu2;
            }
          diffu/=rho_elem(elem);

          // horreur pour NR G2 cas clotaire
          // diffu*=0.5;
          //if (elem==0) Cerr<<"uu "<<diffu<<finl;
          if (transport_rhou)
            {
              double inv_rho2=rho_elem(elem)*rho_elem(elem);
              inv_rho2=1./inv_rho2;
              ml*=inv_rho2;
              for (int d=0; d<dimension; d++)
                vx[d]*=inv_rho2;
            }
          // le .5* c'est pour avoir le meme dt que g2 mais faux
          double dxe=sqrt(ml2);
          if (dxe<min_dx_)
            min_dx_=dxe;
          ml2=diffu/ml2;
          ml*=btd_;
          ml=sqrt(ml2*ml2+ml)+ml2+DMINFLOAT;
          /*      if (ml2>0)
          ml=ml/(sqrt(ml2*ml2+ml)-ml2);
          else ml=-1.;
          */
          if (ml > Max)
            {
              Max=ml;
              // Cerr<<elem << " dx2 "<<dx2<<" "<< G_e<<" "<<1./sqrt(Max)<<finl;
            }
          double ue=sqrt(vx[0]+vx[1]+vx[2]);
          if (ue>max_ue_)
            max_ue_=ue;

          dt_l= 1./(Max+DMINFLOAT);

          if (elem==0) dt2=dt_l;
          if (btd_!=3.)
            {
              double dt0=dt2;
              double s=1.;
              while(s>0)
                {
                  s=-1;
                  for (int d=0; d<dimension; d++)
                    {
                      double c=vx[d]*dt0;
                      if (dabs(c)>1e-16)
                        s+=c/(2.*diffu  +c*btd_);
                    }
                  if (s>0)
                    {
                      dt0*=0.9;
                      Cout<<elem<<" " <<dt_l<<" "<<s<<" "<<dt0<<finl;
                      exit();
                    }
                }
              dt2=min(dt2,dt0);
              dt_l=min(dt2,dt_l);
            }

        }
    min_dx_=mp_min(min_dx_);
    max_ue_=mp_max(max_ue_);
    coefficient_correcteur_supg_.dimensionner(1,1);
    coefficient_correcteur_supg_(0,0)=min_dx_/max_ue_;
    double dt_stab=dt_l;
    dt_stab = Process::mp_min(dt_stab);
    // astuce pour contourner le type const de la methode
    Op_Conv_EF_base& op = ref_cast_non_const(Op_Conv_EF_base,*this);
    op.fixer_dt_stab_conv(dt_stab);


    // Cerr<<" FAUX dt_stab ?? "<<dt_stab<<" "<<1.5*2.5*dt_stab<<finl;

    return dt_stab;
  }

  void Op_Conv_EF::contribue_au_second_membre(DoubleTab& resu ) const
  {
    // on a rien implicite
    ajouter_sous_cond(equation().inconnue().valeurs(),resu,((btd_hors_conv_==1)||btd_impl_),((hourglass_hors_conv_==1)||hourglass_impl_),centre_impl_);
    return;
  }

  void Op_Conv_EF::contribue_au_second_membre_a_la_diffusion(DoubleTab& resu ) const
  {
    ajouter_sous_cond(equation().inconnue().valeurs(),resu,((btd_hors_conv_==0)||btd_impl_),((hourglass_hors_conv_==0)||hourglass_impl_),1);

    return;
  }


  const Champ_base& Op_Conv_EF::get_champ(const Motcle& nom) const
  {
    if (nom=="coefficient_correcteur_supg")
      return coefficient_correcteur_supg_;
    return Op_Conv_EF_base::get_champ(nom);
  }

