#!/bin/bash
for rep in `find * -type d`
do
   seq=$rep.data
   if [ -f $rep/$seq ]
   then
      par=PAR_$rep.data
      if  [ ! -f $rep/$par ] || [ $seq -nt $par ]
      then
         cd $rep
         trust -partition $seq
         cd -
      fi
   fi
done
exit 0
