.PHONY: clean
clean:
	@rm -rfv **/*.egg-info .pytest_cache/ build/
	@find . -name __pycache__ -exec rm -rfv {} +

.PHONY: install
install:
	@pip install -e .

.PHONY: test
test:
#	@pytest -v
	@echo TODO
