#!/bin/bash

# verification status
ok=1
status=0
if [ "`grep 'Arret des process' $1.err`" = "" ]
then
   echo "-> Calculation $1 produced an error !"
   err=`ls -rt $1.err .$1.err 2>/dev/null | tail -1`
   echo "-> Look at the `pwd`/$err file." 
   status=1
else
   if [ "`grep -E 'est inferieur a dt_min|which is less than dt_min' $1.err`" != "" ]
   then
      echo "-> Error ! Problem with $1 dt<dtmin"
      status=1
   fi
fi

tot=`$TRUST_ROOT/Validation/Outils/Genere_courbe/scripts/get_execution_time $1`
[ $? -ne  0 ] &&  status=2
[ $status -ne 0 ] && tot="?"
[ ! -f $1.TU ] && tot="1e9"
#TU=$1.TU
#tot=`grep "Temps total" $1.TU | awk '{printf("%f ", $NF)}' | awk '{print ($1+$2)}'`
#echo $tot 


cas=$1
host=`hostname`
sys=`uname | awk '{print $1}'`

par_pdt=`grep "Secondes / pas de temps" $1.TU| awk '{print $NF}'`
[ "$par_pdt" = "" ] && par_pdt="?"  # on accepte que l'on est pas cette info
nb_elem=`grep -E "Nombre total d'elements|Total number of elements"  $1.err| awk '{print $NF}'`
[ "$nb_elem" = "" ] && nb_elem="-"
echo $cas $host $sys $tot $par_pdt $nb_elem > $1.perf
echo "# cas host systeme temps_total temps_par_pdt nb_elem" >> $1.perf
exit $status
