#!/bin/bash

if [ -f PAR_Pb_multi_reprise_polymac_pb_0000.sauv ] # version PAR
then
	echo "Running PAR_reprise_sauv.data on 2 cpus ..."
	make_PAR.data reprise_sauv.data 2 >poubelle.out
    sed -i 's/Pb_multi_reprise_polymac_pb/PAR_Pb_multi_reprise_polymac_pb/g' PAR_reprise_sauv.data
    trust PAR_reprise_sauv.data 2 1>sauv.out 2>sauv.err

	if [ $? != 0 ] 
	then
		echo "   ===> Error in PAR sauv resume file !"
		exit -1
	else
		echo "   ===> All OK ! PAR simulation well resumed !"
	fi

	if [ -f reprise_sauv.lata ]
    then
        compare_lata_gz PAR_reprise_sauv.lata reprise_sauv.lata 1>verifie2.log 2>&1 || exit -1
        numb_diff2=`awk '$1=="Number"{print $5}' verifie2.log`
        if [[ "$numb_diff2" -gt "0" ]]
        then
          echo "   ===> Error ! Difference between PAR/SEQ sauv resume files !!!"
          exit -1
        else
          echo "   ===> All OK ! No difference between PAR/SEQ sauv resume files !"
        fi
    fi

else # version SEQ
	echo "Running reprise_sauv.data ..."
	trust reprise_sauv.data 1>sauv.out 2>sauv.err

	if [ $? != 0 ] 
	then
		echo "   ===> Error in sauv resume file !"
		exit -1
	else
		echo "   ===> All OK ! Simulation well resumed !"
	fi
fi
