Statistiques d'execution globale : Statistiques d'initialisation du calcul
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       2.52  100.0%                                  1                                  0                        
                                   Preparer calcul (01)       2.52  100.0%                                  1                                  0                        
                          Resoudre (timestep loop) (01)       0.00    0.0%                                  0                                  0                        
                      SolveurSys::resoudre_systeme (01)       0.13    5.0%                                  1                                  0                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.00    0.1%                                246                                  0                        
                                comm:MPI_send_recv (02)       0.00    0.0%                                246                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.01    0.4%                                  8                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.07    2.6%                                  3                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.03    1.0%                                  3                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.02    0.9%                                  3                                  0                        
                                              comm (00)       0.00    0.0%                                246                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.12    5.0%                                 17                                  0                        

Statistiques d'execution globale : Statistiques d'initialisation du calcul
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       1.52   99.9%                                  1                                  0                        
                                   Preparer calcul (01)       1.52   99.9%                                  1                                  0                        
                          Resoudre (timestep loop) (01)       0.00    0.0%                                  0                                  0                        
                      SolveurSys::resoudre_systeme (01)       0.01    0.3%                                  1                                  0                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.00    0.3%                                246                                  0                        
                                comm:MPI_send_recv (02)       0.00    0.1%                                246                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.02    1.1%                                  8                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.11    7.2%                                  3                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.04    2.9%                                  3                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.04    2.7%                                  3                                  0                        
                                              comm (00)       0.00    0.1%                                246                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.21   14.0%                                 17                                  0                        

Statistiques d'execution globale : Statistiques d'initialisation du calcul
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       1.48   99.9%                                  1                                  0                        
                                   Preparer calcul (01)       1.48   99.9%                                  1                                  0                        
                          Resoudre (timestep loop) (01)       0.00    0.0%                                  0                                  0                        
                      SolveurSys::resoudre_systeme (01)       0.01    0.4%                                  1                                  0                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.00    0.3%                                246                                  0                        
                                comm:MPI_send_recv (02)       0.00    0.1%                                246                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.02    1.1%                                  8                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.11    7.3%                                  3                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.04    3.0%                                  3                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.04    2.8%                                  3                                  0                        
                                              comm (00)       0.00    0.1%                                246                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.21   14.3%                                 17                                  0                        

Statistiques d'execution globale : Statistiques de resolution du probleme
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       9.99  100.0%                                  1                                  0                        
                                   Preparer calcul (01)       0.00    0.0%                                  0                                  0                        
                          Resoudre (timestep loop) (01)       9.46   94.8%                                 10                                  0                        
                      SolveurSys::resoudre_systeme (01)       3.54   35.4%                                 70                           1.56e+03                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.08    0.8%                           5.58e+03                                  0                        
                                comm:MPI_send_recv (02)       0.03    0.3%                           5.58e+03                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.03    0.3%                                 19                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.69    6.9%                                 20                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.18    1.8%                                 20                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.17    1.7%                                 20                                  0                        
                                              comm (00)       0.03    0.3%                           5.58e+03                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       1.07   10.8%                                 79                                  0                        

Statistiques d'execution globale : Statistiques d'initialisation du calcul
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       1.69   99.9%                                  1                                  0                        
                                   Preparer calcul (01)       1.69   99.9%                                  1                                  0                        
                          Resoudre (timestep loop) (01)       0.00    0.0%                                  0                                  0                        
                      SolveurSys::resoudre_systeme (01)       0.00    0.3%                                  1                                  0                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.00    0.2%                                246                                  0                        
                                comm:MPI_send_recv (02)       0.00    0.1%                                246                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.01    0.7%                                  8                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.06    3.8%                                  3                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.03    1.7%                                  3                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.03    1.5%                                  3                                  0                        
                                              comm (00)       0.00    0.1%                                246                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.13    7.6%                                 17                                  0                        

Statistiques d'execution globale : Statistiques de resolution du probleme
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       6.17  100.0%                                  1                                  0                        
                                   Preparer calcul (01)       0.00    0.0%                                  0                                  0                        
                          Resoudre (timestep loop) (01)       5.60   90.8%                                 10                                  0                        
                      SolveurSys::resoudre_systeme (01)       2.28   37.0%                                 70                           1.56e+03                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.07    1.1%                           5.58e+03                                  0                        
                                comm:MPI_send_recv (02)       0.03    0.4%                           5.58e+03                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.02    0.3%                                 19                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.29    4.8%                                 20                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.11    1.8%                                 20                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.11    1.7%                                 20                                  0                        
                                              comm (00)       0.03    0.4%                           5.58e+03                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.53    8.6%                                 79                                  0                        

Statistiques d'execution globale : Statistiques d'initialisation du calcul
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       1.78   99.9%                                  1                                  0                        
                                   Preparer calcul (01)       1.78   99.9%                                  1                                  0                        
                          Resoudre (timestep loop) (01)       0.00    0.0%                                  0                                  0                        
                      SolveurSys::resoudre_systeme (01)       0.04    2.5%                                  1                                  0                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.00    0.1%                                246                                  0                        
                                comm:MPI_send_recv (02)       0.00    0.0%                                246                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.00    0.2%                                  8                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.03    1.5%                                  3                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.01    0.6%                                  3                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.01    0.6%                                  3                                  0                        
                                              comm (00)       0.00    0.0%                                246                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.05    2.9%                                 17                                  0                        

Statistiques d'execution globale : Statistiques de resolution du probleme
 Le temps a ete mesure par la methode suivante :
 gettimeofday (elapsed CPU time)
                                        Counter (level)   avg time         (min,max)                avg count (min,max)                  avg qty (min,max)              
                                       Temps total (01)       3.78  100.0%                                  1                                  0                        
                                   Preparer calcul (01)       0.00    0.0%                                  0                                  0                        
                          Resoudre (timestep loop) (01)       3.20   84.7%                                 10                                  0                        
                      SolveurSys::resoudre_systeme (01)       1.28   34.0%                                 70                           1.56e+03                        
                                                m1 (01)       0.00    0.0%                                  0                                  0                        
                                                m2 (01)       0.00    0.0%                                  0                                  0                        
                                                m3 (01)       0.00    0.0%                                  0                                  0                        
                DoubleVect::echange_espace_virtuel (02)       0.05    1.3%                           5.58e+03                                  0                        
                                comm:MPI_send_recv (02)       0.02    0.4%                           5.58e+03                                  0                        
                               io:MPI_send_recv_io (02)       0.00    0.0%                                  0                                  0                        
                                comm:MPI_allreduce (02)       0.00    0.0%                                  0                                  0                        
                                  comm:MPI_barrier (02)       0.00    0.0%                                  0                                  0                        
                                           Scatter (02)       0.00    0.0%                                  0                                  0                        
                          FrontTracking:Check_mesh (03)       0.01    0.4%                                 19                                  0                        
             FrontTracking:Parcours de l'interface (03)       0.19    5.1%                                 20                                  0                        
                  FrontTracking:Calcul_indicatrice (03)       0.07    2.0%                                 20                                  0                        
         FrontTracking:Calculer_distance_interface (03)       0.07    1.8%                                 20                                  0                        
                                              comm (00)       0.02    0.4%                           5.58e+03                                  0                        
                                                io (00)       0.00    0.0%                                  0                                  0                        
                                     FrontTracking (00)       0.35    9.2%                                 79                                  0                        

