#!/bin/bash

get_max()
{
awk 'BEGIN {max=0}{ if ($1!="#") {te=$2; if(te<0) {te=-te };if (te>max) {max=te} }} END {if (max>100) {print "KO"} else { print "OK" }  }' $1 

}


for  dt in `cat liste_dt_2`
  do
  for sch in 1 2 3 4
    do
    max=`get_max test_stab_schema_${dt}_TEMPERATURE_PB_${sch}.son`
    if [ "$max" = "OK" ]
	then
	eval max$sch=$dt
    fi
  done
done
echo  $max1 $max2 $max3 $max4 >stab
