#!/bin/bash

get_max()
{
awk 'BEGIN {max=0}{ if ($1!="#") {if ($2>max) {max=$2} }} END {print max}' $1 

}
cat /dev/null > erreur
for  dt in `cat liste_dt`
do
for sch in 1 2 3 4
do
max=`get_max test_schema_${dt}_ERREUR_TEMPERATURE_PB_${sch}.son`
eval max$sch=$max
done
echo $dt $max1 $max2 $max3 $max4 >> erreur
done
