#!/bin/bash

liste_dt="1.e0 5.e-1 1.e-1 1.e-2 1.e-3"
echo $liste_dt > liste_dt
for dt in $liste_dt
do

sed "s/dt_max	1.e-1/dt_max $dt/" test_schema.data  >  test_schema_${dt}.data
done

liste_dt_2="2.e0 3.e0 4.e0 5.e0 10.e0"
echo $liste_dt_2 > liste_dt_2
for dt in $liste_dt_2
do

sed "s/dt_max	1.e-1/nb_pas_dt_max 3 dt_max $dt/" test_schema.data  >  test_stab_schema_${dt}.data
done
