#!/bin/bash
dest=$1
mkdir -p $1
echo "export PATH=\$TRUST_ROOT${dest#$TRUST_ROOT}/bin:\$PATH" > $dest/env.sh
echo "export PYTHONINTERP_ROOT_DIR=$TRUST_ROOT/exec/python/bin"  >> $dest/env.sh
echo "export PYTHONLIBS_ROOT_DIR=$TRUST_ROOT/exec/python" >> $dest/env.sh

echo "export PYTHONPATH=\$TRUST_ROOT${dest#$TRUST_ROOT}/exec/python/lib/python`python  -c "import sys; print sys.version[:3]"`/site-packages:\$PYTHONPATH" >> $dest/env.sh

echo "export LD_LIBRARY_PATH=\$TRUST_ROOT${dest#$TRUST_ROOT}/lib:\$LD_LIBRARY_PATH" >> $dest/env.sh
