#!/bin/bash
ln -sf $TRUST_ROOT/externalpackages/Python* .
Python=$1 && [ "$1" = "" ] && exit -1
cible=$2 && [ "$2" = "" ] && exit -1
[ "$Python" = "" ] && echo "Python non trouve ici: "`pwd` && exit
Python=${Python%.tgz}
rm -r -f $Python
gunzip -f -c $Python.tgz | tar -xf -
rm -f $Python.tar
cd $Python
export OPT=""
# --enable-shared pour le build de VisIt
./configure --prefix=$cible --disable-ipv6 --enable-shared 
$TRUST_MAKE || exit -1
$TRUST_MAKE python-config || exit -1 # Pour le build de VisIt
make install || exit -1
echo "export PATH=\$TRUST_ROOT${cible#$TRUST_ROOT}/bin:\$PATH" > $2/env.sh
echo "export LD_LIBRARY_PATH=\$TRUST_ROOT${cible#$TRUST_ROOT}/lib:\$LD_LIBRARY_PATH" >> $2/env.sh
cd ..
rm -r -f $Python
