#!/bin/bash
ln -sf $TRUST_ROOT/externalpackages/Python-* .
Python=$1 && [ "$1" = "" ] && exit -1
cible=$2 && [ "$2" = "" ] && exit -1
[ "$Python" = "" ] && echo "Python not found here: "`pwd` && exit
Python=${Python%.tgz}
rm -r -f $Python
gunzip -f -c $Python.tgz | tar -xf -
rm -f $Python.tar
cd $Python
export OPT=""
# --enable-shared pour le build de VisIt
./configure --prefix=$cible --disable-ipv6 --enable-shared 
$TRUST_MAKE || exit -1
$TRUST_MAKE python-config || exit -1 # For the build of VisIt
make install || exit -1
cd ..
./create_env $2
rm -r -f $Python
