#!/bin/bash
gnuplot=$1
Build=$TRUST_ROOT/exec/gnuplot/lib
[ ! -d ${Build} ] && echo Creating ${Build} directory && mkdir -p ${Build}

OLDPATH_=$PATH
NEWPATH_=`echo $PATH | sed "s/exec\/python\/bin/exec/g"`
export PATH=$NEWPATH_

# recuperation des packages

for file in `ls $TRUST_ROOT/externalpackages/gnuplot/*`
do
  ln -sf $file .
done
gd=`ls gd-*.tar.gz 2>/dev/null`
let i=0
for package in $gd $gnuplot
do
   echo "***************************************"
   echo "Trying to install ${package%.tar.gz}..."
   echo "***************************************"
   let i=$i+1
   gunzip -c $package > ${package%.gz}
   tar xf ${package%.gz}
   rm -f ${package%.gz}
   cd ${package%.tar.gz}
   if [ $i = 1 ]
   then
      GD=$Build/gd
      ./configure --prefix=$GD 2>&1 | tee gd.log
      # Echec (PNG&ZLIB non ou mal installes sur la machine)
      if [ "`grep 'libpng is required' gd.log`" != "" ]
      then
         rep_gd=`pwd`
         cd ..
         PNG=$Build/png
         ZLIB=$Build/zlib
         # Installation de zlib
         package=`ls zlib-*.tar.gz 2>/dev/null`
         echo "***************************************"
         echo "Trying to install ${package%.tar.gz}..."
         echo "***************************************"
         gunzip -c $package > ${package%.gz};tar xf ${package%.gz};rm -f ${package%.gz};cd ${package%.tar.gz}
         ./configure --prefix=$ZLIB || exit -1
	 $TRUST_MAKE || exit -1
	 make install || exit -1
         cd .. && rm -r -f ${package%.tar.gz}
        
         # Installation de png
         package=`ls libpng-*.tar.gz 2>/dev/null`
         echo "***************************************"
         echo "Trying to install ${package%.tar.gz}..."
         echo "***************************************"
         gunzip -c $package > ${package%.gz};tar xf ${package%.gz};rm -f ${package%.gz};cd ${package%.tar.gz}
         export CFLAGS="-I$ZLIB/include"
         export LDFLAGS="-L$ZLIB/lib"
         ./configure --prefix=$PNG || exit -1
	 $TRUST_MAKE || exit -1
	 make install || exit -1
         cd .. && rm -r -f ${package%.tar.gz}

         # Reconfiguration de gd avec PNG&ZLIB installes
         cd $rep_gd
	 package=$gd
         echo "***************************************"
         echo "Trying to install ${package%.tar.gz}..."
         echo "***************************************"
         export CFLAGS="-I$PNG/include -I$ZLIB/include"
         export LDFLAGS="-L$ZLIB/lib"
         ./configure --prefix=$GD --with-png=$PNG || exit -1
      fi
   else
      # Probleme sur kata en crontab, lib64 pas trouve
      XLIB="" && [ -d /usr/X11R6/lib64 ] && XLIB="--x-lib=/usr/X11R6/lib64" 
      # --without-tutorial car plantage sur is209003 pour un probleme Latex 
      # --without-lisp-files car plantage sur VRH797979.intra.cea.fr car emacs mal installe
      ./configure --prefix=$TRUST_ROOT/exec/gnuplot --with-texdir=$TRUST_ROOT/exec/gnuplot --with-qt=no --without-lua --without-lisp-files --without-tutorial --with-readline=builtin --with-gd=$GD $XLIB || exit -1
   fi
   # 17-05-2019: if you update gnuplot to a new version using cmake, use cmake from conda as is the case for gmsh
   $TRUST_MAKE || exit -1
   make install  || echo error on installation, but we hope that is ok
   cd ..
   rm -r -f ${package%.tar.gz}
done
# on retire les liens 
for file in `ls $TRUST_ROOT/externalpackages/gnuplot/*`
do
 f=`basename $file`
 [ -h $f ] && rm  $f 
done

# Pour avoir la meme palette que gnuplot 4:
echo "set colors classic # Meme palette que gnuplot 4" >> $TRUST_ROOT/exec/gnuplot/share/gnuplot/*/gnuplotrc

export PATH=$OLDPATH_
exit 0
