#!/bin/bash 
cat /dev/null >fin_total
for f in `ls fin_*.out`
do
 data=`echo $f | sed "s/fin_//" | sed s/".out/.data/"`
 nbr_maille=`grep -i nombre_de_noeud $data| $TRUST_Awk '{print ($2-1)*($3-1)*4}'`
 $TRUST_Awk -v nbr_maille=$nbr_maille '{print ( nbr_maille,$2)}' $f >>  fin_total
done
