#!/bin/bash
# on verifie que le cas trouve la solution definie dans le jdd
compare_sonde $1_SOLUTION.son $1_SONDE_VITESSE.son -seuil_erreur 1e-2  > comp.out 2>&1 
[ $? -ne 0 ] && cat comp.out && exit -1

# on verifie que le  resultat est le meme avec une fonction analytique
compare_lata  Champ_fonc_t.lml $1.lml  > compl.out 2>&1
[ $? -ne 0 ] && cat compl.out && exit -1
exit 0
