#!/bin/bash

rm -rf sim_*
LISTE_CAS="sim_1 sim_2 sim_3"

for CAS in $LISTE_CAS; do

  SRCDATA=Cas.data
  POSTRUN=post_run
  SCRIPT=script_postprocess.py
  REP=./$CAS
  mkdir $REP
  DESTDATA=$REP/$SRCDATA

  if test "$CAS" = "sim_1"; then

    cp $SRCDATA $DESTDATA
    cp $POSTRUN $REP/$POSTRUN # this will run sim_2 + sim_3 + python code at the end in sim_3

  elif test "$CAS" = "sim_2"; then # resume 1

    sed "s~sauvegarde binaire sim_1.sauv~sauvegarde binaire sim_2.sauv~;
         s~/\* resume_last_time binaire ../sim_1/sim_1.sauv \*/~resume_last_time binaire ../sim_1/sim_1.sauv~" $SRCDATA > $DESTDATA

  elif test "$CAS" = "sim_3"; then # resume 2
 
    cp $SCRIPT $REP/$SCRIPT

    sed "s~sauvegarde binaire sim_1.sauv~sauvegarde binaire sim_3.sauv~;
         s~/\* resume_last_time binaire ../sim_1/sim_1.sauv \*/~resume_last_time binaire ../sim_2/sim_2.sauv~" $SRCDATA > $DESTDATA 

  fi
done

