/*****************************************************************************
*
* Copyright (c) 2000 - 2009, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400124
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtsondeFileFormat.C                           //
// ************************************************************************* //

#include <avtsondeFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>
#include <vtkCellType.h>
#include <strstream>

using     std::string;
using std::istrstream;

#define MAXLINE 100000


// ****************************************************************************
//  Method: avtsondeFileFormat constructor
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

avtsondeFileFormat::avtsondeFileFormat(const char *filename)
    : avtMTSDFileFormat(&filename, 1)
{
  coord=0;
  dim=-1;
  nom=filename;
  namevar="MESH";

    // INITIALIZE DATA MEMBERS
  //const char * nom=filename;
  char* buf=new char[MAXLINE+1];
   
 {
  FILE* fic;
  if ( (fic = fopen (nom.c_str(), "r")) == NULL){
    cerr<< "Erreur a l'ouverture du fichier "<< nom<<endl;
    throw;
  } 
 
  fgets(buf,MAXLINE,fic);
  if (buf[0]!='#') 
    {
      cerr<<"premiere ligne de " << nom <<" ne commence pas par # "<<endl;
      throw;
    }
  fgets(buf,MAXLINE,fic);
  dim=-1;
  if (strlen(buf)>=MAXLINE-1)
    {
      cerr<<"strlen(buf) too small "<<endl;throw;
    }
  // on regarde si on a z=
  {
    char* marq=strstr(buf,"z=");
    if (marq!=NULL)  dim=3;
  }
  if (dim==-1)
   {
    char* marq=strstr(buf,"y=");
    if (marq!=NULL)  dim=2;
   }
  if (dim==-1)
    {
    char* marq=strstr(buf,"x=");
    if (marq!=NULL)  
      dim=1;
    else
      { cerr<<"pb "<< buf << " ne ocntient pas x= "<<endl;throw; }
    }
  

  char* marq=strstr(buf,"x=");
  nb_points=0;
  int decal=0;
  while (marq!=NULL)
    {
      nb_points++;
     
      decal=strlen(buf)-strlen(marq)+1;
      marq=strstr(buf+decal,"x=");
    }
  cerr << " nombre de points "<< nb_points<<endl;
  // on compte le nombre de x=
  cerr<<" Dimension "<<dim<<endl;
  coord=new double[dim*nb_points];
  {
    istrstream in(buf);
    string bid;
    in >> bid; in>>bid;
    for (int i=0;i<nb_points;i++)
      {
     for (int d=0;d<dim;d++)
       {
	 in >> bid;  // cerr<<bid<<endl;
	 in >> coord[i*dim+d];
	 // cerr<<i<< " "<<d<<" "<<coord[i+dim*d] <<endl; 
       }
     //if (i==1) {cerr<<buf<<endl;throw(0); }
      }
    
    
    //cerr<<" la "<<coord[300]<<" "<<coord[301]<<" "<<coord[302]<<endl;
  }
  for (int i=0;i<2;i++)
    {
      fgets(buf,MAXLINE,fic);
      if (buf[0]!='#') 
	{
	  cerr<<"premiere ligne de " << nom <<" ne commence pas par # "<<endl;
	  throw;
	}
    }
 
  nbtime=1;
  fgets(buf,MAXLINE,fic);
  int nbc=0;
  {
    istrstream in(buf);
    double toto;
    while (!in.eof())
      {
	in >> toto;
	nbc++;
	//cerr<<toto<<endl;
	
      }
  }
  cerr<<" NBC "<<nbc<<" "<<(nbc-2.)/nb_points<<endl;
  nb_comp=(nbc-2)/nb_points;
  while (  fgets(buf,MAXLINE,fic)!=NULL )
    {
      if (buf[0]!='\n')
	nbtime++;
      
    }
  cerr<<" nbtime "<<nbtime<<endl;
  fclose(fic);
   
  
 
  }
  // on lit les valeurs
 if (1)
  {
    
    FILE* fic;
    if ( (fic = fopen (nom.c_str(), "r")) == NULL){
      cerr<< "Erreur a l'ouverture du fichier "<< nom<<endl;
      throw;
    } 
    for (int i=0;i<4;i++)
      {
	fgets(buf,MAXLINE,fic);
	if (buf[0]!='#') 
	  {
	    cerr<<"premiere ligne de " << nom <<" ne commence pas par # "<<endl;
	    throw;
	  }
      }
    times.resize(nbtime,0);
    val=new float[nb_comp*nb_points*nbtime];
    for (int t=0;t<nbtime;t++)
      {
	float* value=&(val[nb_points*nb_comp*t]);
	fgets(buf,MAXLINE,fic);
	if (buf[0]=='#') 
	  {
	    cerr<<"premiere ligne de " << nom <<"  commence par # "<<endl;
            throw;
	  }
	istrstream in(buf);
	in >> times[t];
	for (int p=0;p<nb_points;p++)
	  for (int c=0;c<nb_comp;c++)
	    {
	      in >> value[p*nb_comp+c];
	    }
      }
  }
  delete [] buf;
  

}
avtsondeFileFormat::~avtsondeFileFormat()
{
  
  if (coord) delete []  coord;
  coord=0;
  
}


// ****************************************************************************
//  Method: avtEMSTDFileFormat::GetNTimesteps
//
//  Purpose:
//      Tells the rest of the code how many timesteps there are in this file.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

int
avtsondeFileFormat::GetNTimesteps(void)
{
  if (nbtime==0) return 1;
  return nbtime;
}

void        avtsondeFileFormat::GetTimes(std::vector<double> & tim)
{
  tim=times;
}

// ****************************************************************************
//  Method: avtsondeFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

void
avtsondeFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtsondeFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

void
avtsondeFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md, int timeState)
{



  avtMeshType mt = AVT_POINT_MESH;
  int nblocks = 1;  //<-- this must be 1 for STSD
  int block_origin = 0;
  int spatial_dimension = dim;
  int topological_dimension = 0;
  double *extents = NULL;
  //
  // Here's the call that tells the meta-data object that we have a mesh:
  //
  AddMeshToMetaData(md, namevar, mt, extents, nblocks, block_origin,
		    spatial_dimension, topological_dimension);
    //
  
 
    // CODE TO ADD A SCALAR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
  if (nb_comp==1)
    AddScalarVarToMetaData(md, "value", "MESH", AVT_NODECENT);
  else
    AddVectorVarToMetaData(md,"value","MESH", AVT_NODECENT,nb_comp);
    //

    //
    // CODE TO ADD A VECTOR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    // int vector_dim = 2;
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
    // AddVectorVarToMetaData(md, varname, mesh_for_this_var, cent,vector_dim);
    //

    //
    // CODE TO ADD A TENSOR VARIABLE
    //
    // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
    // string varname = ...
    // int tensor_dim = 9;
    //
    // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
    // avtCentering cent = AVT_NODECENT;
    //
    //
    // Here's the call that tells the meta-data object that we have a var:
    //
    // AddTensorVarToMetaData(md, varname, mesh_for_this_var, cent,tensor_dim);
    //

    //
    // CODE TO ADD A MATERIAL
    //
    // string mesh_for_mat = meshname; // ??? -- could be multiple meshes
    // string matname = ...
    // int nmats = ...;
    // vector<string> mnames;
    // for (int i = 0 ; i < nmats ; i++)
    // {
    //     char str[32];
    //     sprintf(str, "mat%d", i);
    //     -- or -- 
    //     strcpy(str, "Aluminum");
    //     mnames.push_back(str);
    // }
    // 
    // Here's the call that tells the meta-data object that we have a mat:
    //
    // AddMaterialToMetaData(md, matname, mesh_for_mat, nmats, mnames);
    //
    //
    // Here's the way to add expressions:
    //Expression momentum_expr;
    //momentum_expr.SetName("momentum");
    //momentum_expr.SetDefinition("{u, v}");
    //momentum_expr.SetType(Expression::VectorMeshVar);
    //md->AddExpression(&momentum_expr);
    //Expression KineticEnergy_expr;
    //KineticEnergy_expr.SetName("KineticEnergy");
    //KineticEnergy_expr.SetDefinition("0.5*(momentum*momentum)/(rho*rho)");
    //KineticEnergy_expr.SetType(Expression::ScalarMeshVar);
    //md->AddExpression(&KineticEnergy_expr);
    //
}


// ****************************************************************************
//  Method: avtsondeFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      timestate   The index of the timestate.  If GetNTimesteps returned
//                  'N' time steps, this is guaranteed to be between 0 and N-1.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

vtkDataSet *
avtsondeFileFormat::GetMesh(int timestate, const char *meshname)
{
  vtkUnstructuredGrid *ugrid = vtkUnstructuredGrid::New();
  vtkPoints *points = vtkPoints::New();
  int nnodes=nb_points;
  points->SetNumberOfPoints(nnodes);
  // const double*  coords = coord;
  float* pts = (float *) points->GetVoidPointer(0);
  
  
  for (int i = 0; i < nnodes; i++) {
    for (int d=0;d<2;d++)
      pts[i*3+d]   = coord[i*dim+d];
  }
  if (dim==3)
    for (int i = 0; i < nnodes; i++) 
      pts[i*3+2]   = coord[i*dim+2];
  else
     for (int i = 0; i < nnodes; i++) 
       pts[i*3+2]   = 0;
  ugrid->SetPoints(points);
  points->Delete();
 
  
  // Cells are implicit. Create them:
  int type_cell=VTK_VERTEX;
  int nverts=1;
  vtkIdType *verts = new vtkIdType[nverts];
  ugrid->Allocate(nnodes);
  for (int i = 0; i < nnodes; i++) {
    verts[0] = i;
    ugrid->InsertNextCell(type_cell, nverts, verts);
  }
  delete [] verts;
  return ugrid;
  // YOU MUST IMPLEMENT THIS
}


// ****************************************************************************
//  Method: avtsondeFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      varname    The name of the variable requested.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

vtkDataArray *
avtsondeFileFormat::GetVar(int timestate, const char *varname)
{
  float* value=&(val[nb_points*nb_comp*timestate]);
  vtkFloatArray *rv = vtkFloatArray::New();
  int ntuples = nb_points*nb_comp;
  rv->SetNumberOfTuples(ntuples);
  float * data = rv->GetPointer(0);
  for (int i = 0; i < ntuples; i++) 
    data[i] = value[i];
  return rv;
  throw (0);
  return GetVar(timestate,varname);
  //  YOU MUST IMPLEMENT THIS
      
    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a scalar variable, here is some code that may be helpful.
    //
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // rv->SetNumberOfTuples(ntuples);
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      rv->SetTuple1(i, VAL);  // you must determine value for ith entry.
    // }
    //
    // return rv;
    //
}


// ****************************************************************************
//  Method: avtsondeFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      varname    The name of the variable requested.
//
//  Programmer: fauchet -- generated by xml2avt
//  Creation:   Tue Jun 22 07:40:56 PDT 2010
//
// ****************************************************************************

vtkDataArray *
avtsondeFileFormat::GetVectorVar(int timestate, const char *varname)
{
  //    YOU MUST IMPLEMENT THIS
  vtkFloatArray *rv = vtkFloatArray::New();
  int ntuples = nb_points;
  float* value=&(val[nb_points*nb_comp*timestate]);
  rv->SetNumberOfComponents(3);
  rv->SetNumberOfTuples(ntuples);
  //  float * data = rv->GetPointer(0);
  float* data= rv->WritePointer(0,3*ntuples);
  for (int i = 0; i < ntuples; i++)
    for (int j = 0; j < 3; j++)
      data[i*3+j] = (j<dim) ? value[i*nb_comp+j] : 0.;
 
  return rv;
  throw (0);
  return GetVar(timestate,varname);
    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a vector variable, here is some code that may be helpful.
    //
    // int ncomps = YYY;  // This is the rank of the vector - typically 2 or 3.
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // int ucomps = (ncomps == 2 ? 3 : ncomps);
    // rv->SetNumberOfComponents(ucomps);
    // rv->SetNumberOfTuples(ntuples);
    // float *one_entry = new float[ucomps];
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      int j;
    //      for (j = 0 ; j < ncomps ; j++)
    //           one_entry[j] = ...
    //      for (j = ncomps ; j < ucomps ; j++)
    //           one_entry[j] = 0.;
    //      rv->SetTuple(i, one_entry); 
    // }
    //
    // delete [] one_entry;
    // return rv;
    //
}
