      SUBROUTINE MFFTP1(W,NM,IERR)
*
*   PURPOSE :
*     FACTORIZATION OF NM STORING THE POWERS OF EACH FACTOR IN W
*     ( NM = 2**W(1)*3**W(2)*... )
*     THE MAXIMUM FACTOR FOUND  IS STORED IN W(14)
*
      PARAMETER (MAXFAC=3)
      INTEGER W(14),FACTOR(MAXFAC)
      INTEGER IDERR,FACERR,TBERR
      PARAMETER (IDERR=1,FACERR=2,TBERR=3)
      DATA (FACTOR(I),I=1,MAXFAC)/2,3,5/
      N=NM
      DO 100 I=1,MAXFAC
      W(I)=0
 10   IF(MOD(N,FACTOR(I)).EQ.0)THEN
      W(I)=W(I)+1
      N=N/FACTOR(I)
      GOTO 10
      ENDIF
      IF(N.EQ.1)GOTO 200
100   CONTINUE
      IERR=FACERR
      RETURN
200   W(14)=I
      END
