      SUBROUTINE MFFTP3(INDX,I1,MX,NX,LX)
*
*     THIS SUBROUTINE PERFORMS A "BIT REVERSAL" PERMUTATION
*
      INTEGER INDX(MX,NX,LX),I1(MX,LX,NX)
 
 
      DO 1 NU=1,NX
      DO 1 MU=1,MX
      DO 1 LAM=1,LX
        I1(MU,LAM,NU)=INDX(MU,NU,LAM)
1     CONTINUE
      END
