#!/bin/bash
jdd=PAR_GPU_Aware_MPI
if [ -f $jdd.TU ]
then
   [ "$TRUST_MPI_GPU_AWARE" = 0 ] && echo "No GPU-Aware MPI version detected." && exit 0
   echo "GPU-Aware MPI detected! Enable device-device communications in TRUST:"
   jdd2=enable_$jdd
   cp $jdd.data $jdd2.data
   NP=`ls DOM*.Zones | wc -l`
   TRUST_USE_MPI_GPU_AWARE=1 trust $jdd2 $NP 1>$jdd2.out_err 2>&1 || exit -1
   echo "-----------------------------------------------------------------------------------------------------------------------"
   echo "TRUST use MPI communications:                                 | TRUST use device communications:"
   sdiff $jdd.TU $jdd2.TU | grep -e "GPU:"
   sdiff $jdd.TU $jdd2.TU | grep -e "Secondes / pas de temps"   
   sdiff $jdd.TU $jdd2.TU | grep -e "Secondes / solveur"
   grep "Creating AMG" $jdd2.out_err
fi
