#!/bin/bash

source $TRUST_ROOT/env_for_python.sh
# ND : running using mpirun is mandatory if:
#  1. TRUST built using openmpi
#  2. running in parallel
# I use mpirun since test case fails on orcus and on other installs using openmpi
# Remark: test fails if no petsc since not able to build icoco_swig...
mpirun -np 1 python main.py > main.out

if [ $? -eq 0 ]
then
   echo OK > is_ok
else
   rm -f is_ok
fi

