#!/bin/bash
cas=${1%.data}

# Premiere convergence seulement
ncomp=1
echo awk -v ncomp=$ncomp -v res=$cas.res -f ../res.awk $cas.out
awk -v ncomp=$ncomp -v res=$cas.res -f ../res.awk $cas.out
# Memoire:
awk '/Total Memory Usage/ {setup=$4} /Maximum Memory Usage:/ {solve=$4} END { print "setup solve";printf("%.3f %.3f\n",solve,setup) }' $cas.out 1>$cas.mem
awk '/AmgX/ && /copy/ && /on GPU/ {copy=$NF} /solve: / && (NF==3) {solve=$2}    END { print "copy solve";printf("%.3f %.3f\n",copy,solve) }' $cas.out 1>$cas.cpu
awk '/RAM taken by/ {i++;print i" "$(NF-1)}' $cas.out 1>$cas.ram

memory_gpu=`awk '/Total amount of global memory/ {print $6}' $TRUST_ROOT/env/card.log 2>/dev/null` && [ "$memory_gpu" = "" ] && memory_gpu=0
name_gpu=`awk -F\" '/Device / {print $2}' $TRUST_ROOT/env/card.log 2>/dev/null` && [ "$name_gpu" = "" ] && name_gpu="GPU"

