#!/bin/bash
org=`pwd`
cd $SALOME_COMPOSANTS/LANCE_TEST
. environ.sh
cd $org

cas=tout
[ "$1" != "" ] && cas=$1 

make
status=$?
[ $status -ne 0 ] &&echo pb compil && exit $status
mkdir model
rm -rf model/*
cp $cas.prep model
cd model
../../xprepro ${cas}.prep sal
python ${cas}.py
../../xprepro ${cas}.prep 1
../postverif ${cas}_1000.brep 1000
status=$?
[ $status -ne 0 ] &&echo pb 1000 && exit $status
../postverif ${cas}_2000.brep 2000
status=$?
[ $status -ne 0 ] &&echo pb 2000 && exit $status
exit 0
