#!/bin/bash
org=$1
[ "$org" = "" ] && org="."
mkdir -p build
# option -L est importante pour copier les liens en fichier
echo $ECHO_OPTS "========================================================"
echo $ECHO_OPTS "-> Copy src directory files to the build directory... \c"
rsync -rL $org/src/* build
echo OK
echo $ECHO_OPTS "========================================================"
cd build

chmod -R +w *
if [ -f prepare ]
then
   echo $ECHO_OPTS "==============================================="
   echo $ECHO_OPTS "-> Run prepare script in the build directory..."
   echo $ECHO_OPTS "==============================================="
   chmod +x prepare
   # Detection pour empecher que le script triou, trust, make_PAR.data ou $exec soit utilise dans le prepare
   warning=1
   if [ "`grep 'triou ' ./prepare`" != "" ] || [ "`grep 'trust ' ./prepare`" != "" ] || [ "`grep '\$exec ' ./prepare`" != "" ] || [ "`grep 'make_PAR.data ' ./prepare`" != "" ]
   then
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" 
      echo "You should not run a calculation or partition a mesh in the prepare script."
      echo "Use pre_run scripts instead for this task."
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      [ "$warning" = 0 ] && exit -1
   fi
   ./prepare || exit -1
fi
chmod -R +w *
exit 0
