//TRUST_NO_INDENT
/****************************************************************************
* Copyright (c) 2015 - 2016, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
//
// File      : IJK_Field_simd_tools.h
// Directory : $IJK_ROOT/src/IJK/OpVDF
//
/////////////////////////////////////////////////////////////////////////////
//
// WARNING: DO NOT EDIT THIS FILE! Only edit the template file IJK_Field_simd_tools.h.P
//
#ifndef IJK_Field_simd_tools_included
#define IJK_Field_simd_tools_included
#include <IJK_Field.h>
#include <simd_tools.h>

  // ToDo: remove it! Temporary way to respect trust rules (name of the file = name of the class)
   class IJK_Field_simd_tools
   {
public:
     IJK_Field_simd_tools() {}
    ~IJK_Field_simd_tools() {}
   };



/*! @brief This class implements a accessor to IJK_Field values.
 *
 * It provides efficient access to center, left and right neighbours en i, j, and k directions
 *    and checks if i,j,k are within the bounds
 *
 */
class ConstIJK_float_ptr
{
 public:
/*! @brief builds a pointer to field(i,j,k);
 *
 */
  ConstIJK_float_ptr(const IJK_Field_local_float & field, int i, int j, int k) {
    ptr_ = &field(i, j, k);
    j_stride_ = field.j_stride();
    k_stride_ = field.k_stride();
#ifndef NDEBUG
    const int ghost = field.ghost();
    i_min_ = - ghost; 
    i_max_ = field.ni() + ghost;
    j_min_ = - ghost;
    j_max_ = field.nj() + ghost;
    k_min_ = - ghost;
    k_max_ = field.nk() + ghost;
    i_ = i;
    j_ = j;
    k_ = k;
#endif
  }
/*! @brief increments the pointer by j_stride (eg, j = j+1)
 *
 */
  void next_j() {
    ptr_ += j_stride_;
#ifndef NDEBUG
    j_++;
    assert(j_ < j_max_);
#endif
  }
/*! @brief returns field(i+i_offset, j, k)
 *
 */
    void get_center(int i_offset, float & center) const;
/*! @brief returns left=field(i+i_offset-1, j, k) and center=field(i+i_offset, j, k)
 *
 */
    void get_left_center_x(int i_offset, float & left, float & center) const;
    void get_center_right_x(int i_offset, float & center, float & right) const;
    void get_left_center_right_x(int i_offset, float & left, float & center, float & right) const;
    void get_left_center_y(int i_offset, float & left, float & center) const ;
    void get_center_right_y(int i_offset, float & center, float & right) const ;
    void get_left_center_right_y(int i_offset, float & left, float & center, float & right) const;
    void get_left_center_z(int i_offset, float & left, float & center) const ;
    void get_center_right_z(int i_offset, float & center, float & right) const ;
    void get_left_center_right_z(int i_offset, float & left, float & center, float & right) const ;
    void get_center(int i_offset, Simd_float & center) const ;
    void get_left_center_x(int i_offset, Simd_float & left, Simd_float & center) const;
    void get_center_right_x(int i_offset, Simd_float & center, Simd_float & right) const;
    void get_left_center_right_x(int i_offset, Simd_float & left, Simd_float & center, Simd_float & right) const;
    void get_left_center_y(int i_offset, Simd_float & left, Simd_float & center) const ;
    void get_center_right_y(int i_offset, Simd_float & center, Simd_float & right) const;
    void get_left_center_right_y(int i_offset, Simd_float & left, Simd_float & center, Simd_float & right) const ;
    void get_left_center_z(int i_offset, Simd_float & left, Simd_float & center) const ;
    void get_center_right_z(int i_offset, Simd_float & center, Simd_float & right) const ;
    void get_left_center_right_z(int i_offset, Simd_float & left, Simd_float & center, Simd_float & right) const ;
    void get_leftleft_left_center_right_x(int i_offset, Simd_float & leftleft, Simd_float & left, Simd_float & center, Simd_float & right) const ;
    void get_leftleft_left_center_right_y(int i_offset, Simd_float & leftleft, Simd_float & left, Simd_float & center, Simd_float & right) const ;
    void get_leftleft_left_center_right_z(int i_offset, Simd_float & leftleft, Simd_float & left, Simd_float & center, Simd_float & right) const ;
    void get_leftleft_left_center_right_x(int i_offset, float & leftleft, float & left, float & center, float & right) const ;
    void get_leftleft_left_center_right_y(int i_offset, float & leftleft, float & left, float & center, float & right) const ;
    void get_leftleft_left_center_right_z(int i_offset, float & leftleft, float & left, float & center, float & right) const ;
 
    void get_left_center_xy(int i_offset, Simd_float &leftx_lefty, Simd_float &leftx_centery, Simd_float &centerx_lefty, Simd_float &centerx_centery);
    void get_left_center_xz(int i_offset, Simd_float &leftx_leftz, Simd_float &leftx_centerz, Simd_float &centerx_leftz, Simd_float &centerx_centerz);
 
    void get_left_center_yx(int i_offset, Simd_float &lefty_leftx, Simd_float &lefty_centerx, Simd_float &centery_leftx, Simd_float &centery_centerx);
    void get_left_center_yz(int i_offset, Simd_float &lefty_leftz, Simd_float &lefty_centerz, Simd_float &centery_leftz, Simd_float &centery_centerz);
 
    void get_left_center_zx(int i_offset, Simd_float &leftz_leftx, Simd_float &leftz_centerx, Simd_float &centerz_leftx, Simd_float &centerz_centerx);
    void get_left_center_zy(int i_offset, Simd_float &leftz_lefty, Simd_float &leftz_centery, Simd_float &centerz_lefty, Simd_float &centerz_centery);
 protected:
  const float *ptr_; // pointer to the current location inside the IJK_Field
  int j_stride_; // local copy of field_.j_stride()
  int k_stride_; // idem
#ifndef NDEBUG
  // legal bounds
  int i_min_, i_max_, j_min_, j_max_, k_min_, k_max_;
  // current location of ptr_
  int i_, j_, k_;
#endif
};

// We can automaticaly cast an IJK_float_ptr to a constIJK_float_ptr but not reversed.
class IJK_float_ptr : public ConstIJK_float_ptr
{
 public:
  IJK_float_ptr(IJK_Field_local_float & field, int i, int j, int k): ConstIJK_float_ptr(field, i, j, k) { 
  }
/*! @brief Performs the assignment: field(i+i_offset,j,k) = val
 *
 */
  void put_val(int i_offset, const float & val) {
    assert(i_ + i_offset >= i_min_ && i_ + i_offset < i_max_);
    // cast en non const ok car on avait un IJK_Field_float non const au depart
    ((float*)ptr_)[i_offset] = val;
  }
  void put_val(int i_offset, const Simd_float & val) {
    assert(i_ + i_offset >= i_min_ && i_ + i_offset < i_max_);
    SimdPut((float*)ptr_ + i_offset, val);
  }
};


/*! @brief This class implements a accessor to IJK_Field values.
 *
 * It provides efficient access to center, left and right neighbours en i, j, and k directions
 *    and checks if i,j,k are within the bounds
 *
 */
class ConstIJK_double_ptr
{
 public:
/*! @brief builds a pointer to field(i,j,k);
 *
 */
  ConstIJK_double_ptr(const IJK_Field_local_double & field, int i, int j, int k) {
    ptr_ = &field(i, j, k);
    j_stride_ = field.j_stride();
    k_stride_ = field.k_stride();
#ifndef NDEBUG
    const int ghost = field.ghost();
    i_min_ = - ghost; 
    i_max_ = field.ni() + ghost;
    j_min_ = - ghost;
    j_max_ = field.nj() + ghost;
    k_min_ = - ghost;
    k_max_ = field.nk() + ghost;
    i_ = i;
    j_ = j;
    k_ = k;
#endif
  }
/*! @brief increments the pointer by j_stride (eg, j = j+1)
 *
 */
  void next_j() {
    ptr_ += j_stride_;
#ifndef NDEBUG
    j_++;
    assert(j_ < j_max_);
#endif
  }
/*! @brief returns field(i+i_offset, j, k)
 *
 */
    void get_center(int i_offset, double & center) const;
/*! @brief returns left=field(i+i_offset-1, j, k) and center=field(i+i_offset, j, k)
 *
 */
    void get_left_center_x(int i_offset, double & left, double & center) const;
    void get_center_right_x(int i_offset, double & center, double & right) const;
    void get_left_center_right_x(int i_offset, double & left, double & center, double & right) const;
    void get_left_center_y(int i_offset, double & left, double & center) const ;
    void get_center_right_y(int i_offset, double & center, double & right) const ;
    void get_left_center_right_y(int i_offset, double & left, double & center, double & right) const;
    void get_left_center_z(int i_offset, double & left, double & center) const ;
    void get_center_right_z(int i_offset, double & center, double & right) const ;
    void get_left_center_right_z(int i_offset, double & left, double & center, double & right) const ;
    void get_center(int i_offset, Simd_double & center) const ;
    void get_left_center_x(int i_offset, Simd_double & left, Simd_double & center) const;
    void get_center_right_x(int i_offset, Simd_double & center, Simd_double & right) const;
    void get_left_center_right_x(int i_offset, Simd_double & left, Simd_double & center, Simd_double & right) const;
    void get_left_center_y(int i_offset, Simd_double & left, Simd_double & center) const ;
    void get_center_right_y(int i_offset, Simd_double & center, Simd_double & right) const;
    void get_left_center_right_y(int i_offset, Simd_double & left, Simd_double & center, Simd_double & right) const ;
    void get_left_center_z(int i_offset, Simd_double & left, Simd_double & center) const ;
    void get_center_right_z(int i_offset, Simd_double & center, Simd_double & right) const ;
    void get_left_center_right_z(int i_offset, Simd_double & left, Simd_double & center, Simd_double & right) const ;
    void get_leftleft_left_center_right_x(int i_offset, Simd_double & leftleft, Simd_double & left, Simd_double & center, Simd_double & right) const ;
    void get_leftleft_left_center_right_y(int i_offset, Simd_double & leftleft, Simd_double & left, Simd_double & center, Simd_double & right) const ;
    void get_leftleft_left_center_right_z(int i_offset, Simd_double & leftleft, Simd_double & left, Simd_double & center, Simd_double & right) const ;
    void get_leftleft_left_center_right_x(int i_offset, double & leftleft, double & left, double & center, double & right) const ;
    void get_leftleft_left_center_right_y(int i_offset, double & leftleft, double & left, double & center, double & right) const ;
    void get_leftleft_left_center_right_z(int i_offset, double & leftleft, double & left, double & center, double & right) const ;
 
    void get_left_center_xy(int i_offset, Simd_double &leftx_lefty, Simd_double &leftx_centery, Simd_double &centerx_lefty, Simd_double &centerx_centery);
    void get_left_center_xz(int i_offset, Simd_double &leftx_leftz, Simd_double &leftx_centerz, Simd_double &centerx_leftz, Simd_double &centerx_centerz);
 
    void get_left_center_yx(int i_offset, Simd_double &lefty_leftx, Simd_double &lefty_centerx, Simd_double &centery_leftx, Simd_double &centery_centerx);
    void get_left_center_yz(int i_offset, Simd_double &lefty_leftz, Simd_double &lefty_centerz, Simd_double &centery_leftz, Simd_double &centery_centerz);
 
    void get_left_center_zx(int i_offset, Simd_double &leftz_leftx, Simd_double &leftz_centerx, Simd_double &centerz_leftx, Simd_double &centerz_centerx);
    void get_left_center_zy(int i_offset, Simd_double &leftz_lefty, Simd_double &leftz_centery, Simd_double &centerz_lefty, Simd_double &centerz_centery);
 protected:
  const double *ptr_; // pointer to the current location inside the IJK_Field
  int j_stride_; // local copy of field_.j_stride()
  int k_stride_; // idem
#ifndef NDEBUG
  // legal bounds
  int i_min_, i_max_, j_min_, j_max_, k_min_, k_max_;
  // current location of ptr_
  int i_, j_, k_;
#endif
};

// We can automaticaly cast an IJK_double_ptr to a constIJK_double_ptr but not reversed.
class IJK_double_ptr : public ConstIJK_double_ptr
{
 public:
  IJK_double_ptr(IJK_Field_local_double & field, int i, int j, int k): ConstIJK_double_ptr(field, i, j, k) { 
  }
/*! @brief Performs the assignment: field(i+i_offset,j,k) = val
 *
 */
  void put_val(int i_offset, const double & val) {
    assert(i_ + i_offset >= i_min_ && i_ + i_offset < i_max_);
    // cast en non const ok car on avait un IJK_Field_double non const au depart
    ((double*)ptr_)[i_offset] = val;
  }
  void put_val(int i_offset, const Simd_double & val) {
    assert(i_ + i_offset >= i_min_ && i_ + i_offset < i_max_);
    SimdPut((double*)ptr_ + i_offset, val);
  }
};


#endif
