#!/bin/bash
set -u
# on nettoie
rm -f *lml *med
# on lance trio pour generer le med
$exec test_homard

# Test critere absolu 
# on lance homard
../lance_homard crit_0000.med dom fct 1.8

## on lance la conversion en geom
$exec transf_med

# on reecrit un lml
$exec transf_lml

# on compare
gunzip -c org.lml.gz > org.lml
compare_lata test.lml org.lml
status=$?

# test critere relatif 2%
# on lance homard 
../lance_homard crit_0000.med dom fct  -majcrit   -type_seuil 1 2 

## on lance la conversion en geom
$exec transf_med

# on reecrit un lml
$exec transf_lml

# on compare
gunzip -c org_relat.lml.gz > org_relat.lml
compare_lata test.lml org_relat.lml
status2=$?



../lance_homard crit_0000_raff1.med dom fct  -majcrit  -niter 1  1.71

$exec transf_med
sed "s/crit_0000_raff1.geom/crit_0000_raff2.geom/" transf_lml.data > toto.data
$exec toto
# on compare
gunzip -c org_biraf.lml.gz > org_biraf.lml
compare_lata test.lml org_biraf.lml
status3=$?


[ $status -ne 0 ] && exit $status
[ $status2 -ne 0 ] && exit $satus2
exit $status3
