#!/bin/bash

# Parametres
fichier=`pwd | awk -F"/" '{print $NF}'`
hy=0.004
Pz=0.002
Lx=0.462
Pres=7092750
Rconst=2075.95
Cp=5193
To=673

# Extrait_coupe sur les fichiers
extrait_coupe $fichier SONDE_TEMPERATURE_SORTIE
extrait_coupe $fichier SONDE_TEMPERATURE_SOL_SORTIE
extrait_coupe $fichier SONDE_VITESSE_SORTIE

# Parametre d'adimensionnalisation
# ATTENTION, grep n'est pas bien portable !
Ustar_bas=`grep "4.30555559e-01.*0.00000000e+00.*9.27487429e-04"  $fichier\_pb_Th_Ustar.face | tail -1 | awk '{print $11}'`
Ustar_bas=`awk "BEGIN{printf \"%.2f\", $Ustar_bas}"`
Deq_bas=`grep "4.30555559e-01.*0.00000000e+00.*9.27487429e-04"  $fichier\_pb_Th_Nusselt.face | tail -1 | awk '{print $7}'`
T_bas=`grep -n "0.00000000e+00"  $fichier\_SONDE_TEMPERATURE_SOL_SORTIE.coupe | head -1 | awk -F: '{print $1-1}'`
T_bas=`head -$T_bas  $fichier\_SONDE_TEMPERATURE_SOL_SORTIE.coupe | tail -1 | awk '{print $2}'`
T1=`head -2 $fichier\_SONDE_TEMPERATURE_SORTIE.coupe | tail -1 | awk '{print $2}'`
rho_bas=`awk "BEGIN{print $Pres/$Rconst/$T_bas}"`
mu_bas=`awk "BEGIN{print 0.000000395*$T_bas^0.687}"`
nu_bas=`awk "BEGIN{print $mu_bas/$rho_bas}"`
lambda_bas=`awk "BEGIN{print (0.002774*$T_bas^0.701)}"`
alpha_bas=`awk "BEGIN{print $lambda_bas/($rho_bas*$Cp)}"`
Phy_diff_bas=`awk "BEGIN{print $lambda_bas*($T_bas-($T1))/$Deq_bas*$Lx*$Pz}"`
Tstar_bas=`awk "BEGIN{print $Phy_diff_bas/($rho_bas*$Cp*$Ustar_bas*$Lx*$Pz)}"`
Re_t_bas_Trio=`awk "BEGIN{printf \"%.2f\", $Ustar_bas*$hy/2/$nu_bas}"`
Re_bas_bulk=`awk "BEGIN{print ($Re_t_bas_Trio/0.175)^(8/7)}"`
Re_bas_Dh=`awk "BEGIN{print 4*$Re_bas_bulk}"`
Pr_bas=`awk "BEGIN{print $nu_bas/$alpha_bas}"`

nbl=`wc -l $fichier\_SONDE_TEMPERATURE_SORTIE.coupe | awk '{print $1}'`

# ATTENTION, grep n'est pas bien portable !
Ustar_haut=`grep "4.36973610e-01.*4.00000000e-03.*1.02512615e-03" $fichier\_pb_Th_Ustar.face | tail -1 | awk '{print $11}'`
Ustar_haut=`awk "BEGIN{printf \"%.2f\", $Ustar_haut}"`
Deq_haut=`grep "4.36973610e-01.*4.00000000e-03.*1.02512615e-03" $fichier\_pb_Th_Nusselt.face | tail -1 | awk '{print $7}'`
T_haut=`grep -n "0.00000000e+00" $fichier\_SONDE_TEMPERATURE_SOL_SORTIE.coupe | tail -1 | awk -F: '{print $1+1}'`
T_haut=`head -$T_haut $fichier\_SONDE_TEMPERATURE_SOL_SORTIE.coupe | tail -1 | awk '{print $2}'`
T1=`head -$nbl $fichier\_SONDE_TEMPERATURE_SORTIE.coupe | tail -1 | awk '{print $2}'`
rho_haut=`awk "BEGIN{print $Pres/$Rconst/$T_haut}"`
mu_haut=`awk "BEGIN{print 0.000000395*$T_haut^0.687}"`
nu_haut=`awk "BEGIN{print $mu_haut/$rho_haut}"`
lambda_haut=`awk "BEGIN{print (0.002774*$T_haut^0.701)}"`
alpha_haut=`awk "BEGIN{print $lambda_haut/($rho_haut*$Cp)}"`
Phy_diff_haut=`awk "BEGIN{print $lambda_haut*($T_haut-($T1))/$Deq_haut*$Lx*$Pz}"`
Tstar_haut=`awk "BEGIN{print $Phy_diff_haut/($rho_haut*$Cp*$Ustar_haut*$Lx*$Pz)}"`
Re_t_haut_Trio=`awk "BEGIN{printf \"%.2f\", $Ustar_haut*$hy/2/$nu_haut}"`
Re_haut_bulk=`awk "BEGIN{print ($Re_t_haut_Trio/0.175)^(8/7)}"`
Re_haut_Dh=`awk "BEGIN{print 4*$Re_haut_bulk}"`
Pr_haut=`awk "BEGIN{print $nu_haut/$alpha_haut}"`


# Creation des fichiers resultats : Star_bas.cut ; Star_haut.cut ; ShearStress_bas.dat ; ShearStress_haut.dat ; Tbulk.dat
nb_ligne_vitesse=`wc -l $fichier\_SONDE_VITESSE_SORTIE.coupe | awk '{print $1}'`
i=2
Uplus_bas_max=0
Uplus_bas_bak=0
Uplus_VD_bas_bak=0
rho_sur_rhobas_bak=1
somme_rho_U=0
somme_rho=`awk "BEGIN{print $rho_bas+$rho_haut}"`
somme_UT=0
somme_U=0
while (( i <= nb_ligne_vitesse ))
do
	Y=`head -$i $fichier\_SONDE_VITESSE_SORTIE.coupe | tail -1 | awk '{print $1}'`
	U=`head -$i $fichier\_SONDE_VITESSE_SORTIE.coupe | tail -1 | awk '{print $2}'`
	T=`head -$i $fichier\_SONDE_TEMPERATURE_SORTIE.coupe | tail -1 | awk '{print $2}'`
	rho=`awk "BEGIN{print $Pres/$Rconst/$T}"`
	somme_rho=`awk "BEGIN{print $somme_rho+$rho}"`
	mu=`awk "BEGIN{print 0.000000395*$T^0.687}"`
	rho_sur_rhobas=`awk "BEGIN{print ($rho/$rho_bas)^0.5}"`
	somme_rho_U=`awk "BEGIN{print $somme_rho_U+($rho*$U)}"`
	somme_U=`awk "BEGIN{print $somme_U+$U}"`
	somme_UT=`awk "BEGIN{print $somme_UT+($U*$T)}"`
	moyenne_rho=`awk "BEGIN{print ($rho_sur_rhobas+$rho_sur_rhobas_bak)/2}"`
	Yplus_bas=`awk "BEGIN{print $Y*$Ustar_bas/$nu_bas}"`
	Uplus_bas=`awk "BEGIN{print $U/$Ustar_bas}"`
	Tplus_bas=`awk "BEGIN{print ($T_bas-($T))/$Tstar_bas}"`
	moyenne_rho_dUplus=`awk "BEGIN{print $moyenne_rho*($Uplus_bas-($Uplus_bas_bak))}"`
	Uplus_VD_bas=`awk "BEGIN{print $Uplus_VD_bas_bak+$moyenne_rho_dUplus}"`
	Yplus_SLS_bas=`awk "BEGIN{print $Yplus_bas*$rho_sur_rhobas*$mu_bas/$mu}"`
	Uplus_SLS_bas=`awk "BEGIN{print $Uplus_bas*$rho_sur_rhobas}"`
	Tplus_SLS_bas=`awk "BEGIN{print $Tplus_bas*$rho_sur_rhobas}"`
	imprime=`awk "BEGIN{if(($Uplus_bas_max<$Uplus_bas)&&($Yplus_bas!=0)) print 1; else print 0;}"`
	((i==2)) && echo "# Y+		U+		T+		U+ VD		Y+ SLS		U+ SLS		T+ SLS" > Star_bas.cut
	((imprime==1)) && echo "$Yplus_bas		$Uplus_bas		$Tplus_bas		$Uplus_VD_bas		$Yplus_SLS_bas		$Uplus_SLS_bas		$Tplus_SLS_bas" >> Star_bas.cut
	Uplus_bas_max=`awk "BEGIN{if($Uplus_bas_max<$Uplus_bas) print $Uplus_bas; else print $Uplus_bas_max;}"`
	Uplus_bas_bak=$Uplus_bas
	Uplus_VD_bas_bak=$Uplus_VD_bas
	rho_sur_rhobas_bak=$rho_sur_rhobas
	((i=i+1))
done

U_bulk=`awk "BEGIN{print $somme_rho_U/$somme_rho}"`
T_bulk=`awk "BEGIN{printf \"%.2f\", $somme_UT/$somme_U}"`
rho_bulk=`awk "BEGIN{print $Pres/$Rconst/$T_bulk}"`
mu_bulk=`awk "BEGIN{print 0.000000395*$T_bulk^0.687}"`
nu_bulk=`awk "BEGIN{print $mu_bulk/$rho_bulk}"`
Re_bulk=`awk "BEGIN{printf \"%.2f\", $U_bulk*$hy*$rho_bulk/2/$mu_bulk}"`
Re_t_bulk=`awk "BEGIN{printf \"%.2f\", 0.175*$Re_bulk^(7/8)}"`
U_t_bulk=`awk "BEGIN{printf \"%.2f\", $Re_t_bulk*2*$nu_bulk/$hy}"`

#echo "# Re_bulk	Re_t_bulk	U_t_bulk	Re_t_Trio	Ustar_Trio" > ShearStress_bas.dat
echo "$Re_bulk		$Re_t_bulk		$U_t_bulk		$Re_t_bas_Trio		$Ustar_bas" > ShearStress_bas.dat
#echo "# Re_bulk	Re_t_bulk	U_t_bulk	Re_t_Trio	Ustar_Trio" > ShearStress_haut.dat
echo "$Re_bulk		$Re_t_bulk		$U_t_bulk		$Re_t_haut_Trio		$Ustar_haut" > ShearStress_haut.dat

Nusselt_bas_Trio=`awk "BEGIN{printf \"%.2f\", ($Phy_diff_bas/($T_bas-($T_bulk))/$Lx/$Pz)*$hy/$lambda_bas}"`
Nusselt_haut_Trio=`awk "BEGIN{printf \"%.2f\", ($Phy_diff_haut/($T_haut-($T_bulk))/$Lx/$Pz)*$hy/$lambda_haut}"`
Nusselt_bas_KC=`awk "BEGIN{printf \"%.2f\", 0.04*$Re_bas_bulk^0.8*$Pr_bas^0.3}"`
Nusselt_haut_KC=`awk "BEGIN{printf \"%.2f\", 0.04*$Re_haut_bulk^0.8*$Pr_haut^0.3}"`
Nusselt_bas_C=`awk "BEGIN{printf \"%.2f\", 0.023*$Re_bas_Dh^0.8*$Pr_bas^(1/3)}"`
Nusselt_haut_C=`awk "BEGIN{printf \"%.2f\", 0.023*$Re_haut_Dh^0.8*$Pr_haut^(1/3)}"`
Nusselt_bas_K=`awk "BEGIN{printf \"%.2f\", 0.66*$Nusselt_bas_C}"`
Nusselt_haut_K=`awk "BEGIN{printf \"%.2f\", 0.66*$Nusselt_haut_C}"`
Nusselt_bas_DB=`awk "BEGIN{printf \"%.2f\", 0.024*$Re_bas_Dh^0.8*$Pr_bas^0.4}"`
Nusselt_haut_DB=`awk "BEGIN{printf \"%.2f\", 0.024*$Re_haut_Dh^0.8*$Pr_haut^0.4}"`
Q_bas=`awk "BEGIN{print ($Phy_diff_bas/$Lx/$Pz)/($rho_bas*$Cp*$U_bulk*$T_bas)}"`
Q_haut=`awk "BEGIN{print ($Phy_diff_haut/$Lx/$Pz)/($rho_haut*$Cp*$U_bulk*$T_haut)}"`
Nusselt_bas_Mc=`awk "BEGIN{printf \"%.2f\", 0.021*$Re_bas_bulk^0.8*$Pr_bas^0.4*exp(-90*$Q_bas)}"`
Nusselt_haut_Mc=`awk "BEGIN{printf \"%.2f\", 0.021*$Re_haut_bulk^0.8*$Pr_haut^0.4*exp(-90*$Q_haut)}"`

#echo "# Nu_Trio	Nu Kays & C	Nu Kasagi	Nu Colburn	Nu Dittus Boelter	Nu MacElligot" > Nusselt_bas.dat
echo "$Nusselt_bas_Trio		$Nusselt_bas_KC		$Nusselt_bas_K		$Nusselt_bas_C		$Nusselt_bas_DB			$Nusselt_bas_Mc" > Nusselt_bas.dat
#echo "# Nu_Trio	Nu Kays & C	Nu Kasagi	Nu Colburn	Nu Dittus Boelter	Nu MacElligot" > Nusselt_haut.dat
echo "$Nusselt_haut_Trio		$Nusselt_haut_KC		$Nusselt_haut_K		$Nusselt_haut_C		$Nusselt_haut_DB			$Nusselt_haut_Mc" > Nusselt_haut.dat

DT=`awk "BEGIN{printf \"%.2f\", $T_bulk-($To)}"`
#echo "# T_bulk_oulet	D_T" > Tbulk.dat
echo "$T_bulk		$DT" > Tbulk.dat

((i=nb_ligne_vitesse))
Uplus_haut_max=0
Uplus_haut_bak=0
Uplus_VD_haut_bak=0
rho_sur_rhohaut_bak=1
while (( 2 <= i ))
do
	Y=`head -$i $fichier\_SONDE_VITESSE_SORTIE.coupe | tail -1 | awk '{print $1}'`
	U=`head -$i $fichier\_SONDE_VITESSE_SORTIE.coupe | tail -1 | awk '{print $2}'`
	T=`head -$i $fichier\_SONDE_TEMPERATURE_SORTIE.coupe | tail -1 | awk '{print $2}'`
	rho=`awk "BEGIN{print $Pres/$Rconst/$T}"`
	mu=`awk "BEGIN{print 0.000000395*$T^0.687}"`
	rho_sur_rhohaut=`awk "BEGIN{print ($rho/$rho_haut)^0.5}"`
	moyenne_rho=`awk "BEGIN{print ($rho_sur_rhohaut+$rho_sur_rhohaut_bak)/2}"`
	Yplus_haut=`awk "BEGIN{print ($hy-($Y))*$Ustar_haut/$nu_haut}"`
	Uplus_haut=`awk "BEGIN{print $U/$Ustar_haut}"`
	Tplus_haut=`awk "BEGIN{print ($T_haut-($T))/$Tstar_haut}"`
	moyenne_rho_dUplus=`awk "BEGIN{print $moyenne_rho*($Uplus_haut-($Uplus_haut_bak))}"`
	Uplus_VD_haut=`awk "BEGIN{print $Uplus_VD_haut_bak+$moyenne_rho_dUplus}"`
	Yplus_SLS_haut=`awk "BEGIN{print $Yplus_haut*$rho_sur_rhohaut*$mu_haut/$mu}"`
	Uplus_SLS_haut=`awk "BEGIN{print $Uplus_haut*$rho_sur_rhohaut}"`
	Tplus_SLS_haut=`awk "BEGIN{print $Tplus_haut*$rho_sur_rhohaut}"`
	imprime=`awk "BEGIN{if(($Uplus_haut_max<$Uplus_haut)&&($Yplus_haut!=0)) print 1; else print 0;}"`
	((i==nb_ligne_vitesse)) && echo "# Y+		U+		T+		U+ VD		Y+ SLS		U+ SLS		T+ SLS" > Star_haut.cut
	((imprime==1)) && echo "$Yplus_haut		$Uplus_haut		$Tplus_haut		$Uplus_VD_haut		$Yplus_SLS_haut		$Uplus_SLS_haut		$Tplus_SLS_haut" >> Star_haut.cut
	Uplus_haut_max=`awk "BEGIN{if($Uplus_haut_max<$Uplus_haut) print $Uplus_haut; else print $Uplus_haut_max;}"`
	Uplus_haut_bak=$Uplus_haut
	Uplus_VD_haut_bak=$Uplus_VD_haut
	rho_sur_rhohaut_bak=$rho_sur_rhohaut
	((i=i-1))
done

