#!/bin/bash
# ND : I skip verifie to not have crash if no mpi + 64 bit integers...
[ "$TRUST_INT64" = "1" ] && [ "$TRUST_DISABLE_MPI" = "1" ] && echo "verifie not run since TRUST_INT64=1 and TRUST_DISABLE_MPI=1" && exit 0
# Resolution du systeme par PETSc
# Conversion en matrice PETSc:
for file in `ls *matrix*.mtx 2>/dev/null`
do
   echo -e "Converting $file to ${file%.mtx}.petsc... \c"
   indices=32bit && [ "$TRUST_INT64" = 1 ] && indices=64bit
   python $PETSC_DIR/lib/petsc/bin/PetscBinaryIO.py convert --indices $indices $file || exit -1
   echo "OK!"
done
for file in `ls *matrix*.petsc 2>/dev/null`
do
   ./petsc_matrix.sh -n 1 $file -rhs ONE || exit -1
done
