#!/bin/bash
if [ "$WISH" = "" ]
then
   WISH="$TRUST_ROOT/exec/tcl_tk/bin/wish8.0"
   [ ! -f $WISH ] && WISH=`whereis -b wish | awk '{if (NF>1) print $2}'`
fi
[ ! -f $WISH ]  && echo wish non trouve definir WISH && exit
exec $WISH $TRUST_ROOT/Outils/preray/trio_rayo.tcl $*
