#!/bin/bash
jdd=$1
[ $jdd != cp ] && exit 0
echo "Checking results for $jdd.."
for calcul in `find . -type d -name calcul'?'`
do
   cd $calcul
   # Verification que tout le monde est bien la
   grep TRUST $jdd"_LATA".lata 	|| exit -1 	# lata
   grep GEOM $jdd"_LATA".lata 	    || exit -1 	# lata
   grep $jdd *.son 	 || exit -1 	# son
   grep temps $jdd.dt_ev 	 || exit -1 	# dt_ev
   ls $jdd"_MED_0000.med" || exit -1 # Fichier MED
   ls $jdd*.TU 1>/dev/null 2>&1 && exit -1    # Tous les .TU doivent etre a la racine !
   cd -
done
exit 0

