#!/bin/bash

cp $TRUST_ROOT/tests/EOS/jdd EOS_test_refprop10_R12.data
cp $TRUST_ROOT/tests/EOS/__sample__ EOS_test_refprop10_R12.cpp
sed -i 's/liquid("__MODEL__", "__FLUID__")/liquid("EOS_Refprop10", "R12Liquid")/g' EOS_test_refprop10_R12.cpp
sed -i 's/steam("__MODEL__", "__FLUID__")/steam("EOS_Refprop10", "R12Vapor")/g' EOS_test_refprop10_R12.cpp


$TRUST_CC_BASE -std=c++11 -Wall -o EOS_test_refprop10_R12.x -I$TRUST_EOS_HOME_DIR/include/ -I$TRUST_ROOT/include/ -I$TRUST_ROOT/include/EOS/ EOS_test_refprop10_R12.cpp $TRUST_EOS_HOME_DIR/lib/libeos.a -lgfortran

./EOS_test_refprop10_R12.x &>out

if [ $? -eq 0 ]
then
  echo OK > is_ok
else
  rm -f is_ok
fi

