#!/bin/bash

cp $TRUST_ROOT/tests/EOS/jdd EOS_test_refprop10_R12.data
cp $TRUST_ROOT/tests/EOS/__sample__ EOS_test_refprop10_R12.cpp
sed -i 's/liquid("__MODEL__", "__FLUID__")/liquid("EOS_Refprop10", "R12Liquid")/g' EOS_test_refprop10_R12.cpp
sed -i 's/steam("__MODEL__", "__FLUID__")/steam("EOS_Refprop10", "R12Vapor")/g' EOS_test_refprop10_R12.cpp

# Ajout tirpc comme dans bin/mklibs
tirpc=""
if [ -f $TRUST_EOS_HOME_DIR/lib/pkgconfig/eos.pc ]
then
   [ "`grep tirpc $TRUST_EOS_HOME_DIR/lib/pkgconfig/eos.pc 2>/dev/null`" != "" ] && tirpc="-ltirpc"
else
   # old EOS versions seems to not have eos.pc
   [ "`ldd $TRUST_EOS_HOME_DIR/lib/libeos.so 2>/dev/null | grep libtirpc.so`" != "" ] && tirpc="-ltirpc"
fi


$TRUST_CC_BASE -std=$TRUST_STDCPP -Wall -o EOS_test_refprop10_R12.x -I$TRUST_EOS_HOME_DIR/include/ -I$TRUST_ROOT/include/ -I$TRUST_ROOT/include/EOS/ EOS_test_refprop10_R12.cpp $TRUST_EOS_HOME_DIR/lib/libeos.a $tirpc -lgfortran

./EOS_test_refprop10_R12.x &>out

if [ $? -eq 0 ]
then
  echo OK > is_ok
else
  rm -f is_ok
fi

