#!/bin/bash

#if [ "`diff out out.ref`" != "" ]
#then
#  echo "   ===> Error ! Test case EOS_test_refprop10_R12 KO !"
#  exit -1
#else
#  echo "   ===> All OK for test case EOS_test_refprop10_R12 !"
#fi
