#!/bin/bash
export project_directory=$TRUST_ROOT/Validation/Rapports_automatiques/Verification/PolyMAC
source "$project_directory/share/maquette_decapoly/env_maquette.sh"
python prepare_python.py
python $TRUST_ROOT/bin/KSH/preprocessor.py Rayleigh_Benard_2D.prm.P Rayleigh_Benard_2D.prm
