#!/bin/bash

DIR=`dirname $0`
DIR=`(cd $DIR; pwd)`
. $DIR/IHMTRIO.sh
org=`dirname $1`
org=`(cd $org;pwd)`
file=$org/`basename $1 .data`.data
[ ! -f $file ] && echo creation de $file && echo fin  > $file
#[ "`dirname $1`" = "." ] && file=$org"/"$file
echo $file

if [ "$2" != "" ]
    then 
    reedit=1
else
    reedit=0
    cp $file $file.org
    chmod +w $file.org
fi

cd $(dirname $file) 
filebase=`basename $file .data`
filepy=$filebase.py
file2=$filebase.mod.data
file3=$filebase.mod2.data
rm -f __sa__$filepy*
if [ $reedit -eq 0 ]
    then 
    rm -f $filepy*
pwd
    python -c "from triou import *;list=read_file_data('$filebase.data');write_file_data('$file2',list);write_file_python('$filepy',list)" ; [ $? -ne 0 ] && exit #1>/dev/null
fi


#xdatagui --module=TRIOU $filepy
# utilisation des nouvelles options 0.5.39
xdatagui --module=TRIOU --with-splitter=no --without-menus=Preferences,Window,Modules,Tools,View $filepy


time python -c "from __sa__$filebase import *;from triou import write_file_data,read_file_data;write_file_data('$file3',list_instance);list=read_file_data('$file3')" 1>/dev/null; status=$?
echo $status
if [ $status -ne 0 ]
    then

    echo "You have make a mistake"
    diff $file2 $file3 | less
#echo "on reedite OK?"
#		read OK

#		cp __sa__.py $filepy	
#		cd $org
#		echo $0 $* 1
#		$0 $* 1
#		cd $TMP
fi
echo "iii" $file2 $file3
res=`diff $file2 $file3`
if [ "$res" != "" ]
    then
    diff $file2 $file3
    if [ $status -ne 0 ]
	then

	echo "You have make a mistake"
    fi
    echo "Do you accept the differences ? (y/n/R)"
    read ok
    if [ "$ok" = "y" ] || [ "$ok" = "Y" ]
	then
	
	cp $file3 $file
	
    else 
	if [ "$ok" = "n" ] || [ "$ok" = "N" ]
	    then
	    cp $file.org $file
	    exit
	else
	    echo "on reedite"
	    cp __sa__$filepy $filepy	
	    
	    echo $0 $* 1
	    $0 $* 1
	    
	fi
    fi	
else
    echo "pas de difference"
fi
rm $file2 $file3 __sa__${filepy}*  $filepy
ls -lrt | tail -2
