#!/bin/bash

cp $TRUST_ROOT/tests/EOS/jdd CoolProp_test_simple_1.data

$TRUST_CC_BASE -std=c++20 -o CoolProp_test_simple_1.x -I$TRUST_ROOT/include/ -I$TRUST_ROOT/include/CoolProp/ CoolProp_test_simple_1.cpp $TRUST_COOLPROP_HOME_DIR/build/libCoolProp.a

./CoolProp_test_simple_1.x &>out

if [ "`diff out out.ref`" != "" ]
then
  rm -f is_ok
else
  echo OK > is_ok
fi
