#!/bin/bash


list="10 20 40 80 160"
cas="amont muscl ef_stab amont_old centre"
echo $cas > listcas

stdfacsecs="0.01 " #0.001"

#list="10"
#stdfacsecs="1"

facsecs="$stdfacsecs"
sed "s/%list%/$list/; s/%cas%/$cas/;s/%extfacsecs%/$facsecs/;s/%facsecs%/$stdfacsecs/" conv.prm.P.m  > conv.prm.P

python $TRUST_ROOT/bin/KSH/preprocessor.py conv.prm.P conv.prm

echo > ll
for K in $cas
do
for resol in $list
  do
  nn=`echo $resol+1|bc `
    mkdir -p  ${K}_${resol}
    KK=$K
    [ $K = "ef_stab" ] &&  KK="ef_stab { TdivU }"
    sed "s/11 11/$nn $nn/;s/centre4/$KK/" base.data >  ${K}_${resol}/cas.data
   sed "s/RESOL/${resol}/;s/CAS/$K/" post_run >   ${K}_${resol}/post_run
   echo ${K}_${resol}/cas.data >> ll
done
done
grep -v _10 ll > liste_cas_exclu_nr
 
