#!/bin/bash

source $TRUST_ROOT/Outils/ICoCo/ICoCo_src/env_MEDICoCo.sh

trust -check CouplageFluideSolide_jdd1
if [ $? -eq 0 ]
then
  echo OK > is_ok1
else
  rm -f is_ok1
fi

trust -check CouplageFluideSolide_jdd2
if [ $? -eq 0 ]
then
  echo OK > is_ok2
else
  rm -f is_ok2
fi

