all: clean
	pdflatex Tutorial_solutions.tex
	pdflatex Tutorial_solutions.tex
	mv Tutorial_solutions.pdf ..


clean:
	@echo "Removing compilation files and pdf"
	@rm -f *.log *.aux *.dvi *.toc *.out *.pdf
