#!/bin/bash
# Script d'installation
install_OpenBlas()
{
   #########################
   # Installation d'OpenBLAS
   #########################
   package=OpenBLAS-$version_openblas.tar.gz
   lib=libopenblas.a

   # Installation
   rm -r -f *-OpenBLAS-*
   echo "Installation of $package (USE_THREAD=$PETSC_HAVE_OPENMP)..."
   gunzip -f -c $package | tar -xf -
   cd OpenBLAS-$version_openblas
   $TRUST_MAKE CC=$TRUST_cc FC=$TRUST_F77 USE_THREAD=$PETSC_HAVE_OPENMP

   # On copie la librairie si elle existe sinon on sort
   if [ -f $lib ]
   then
      cp $lib ..
      cd ..
      # On fait des liens
      ln -sf $lib libblas.a
      ln -sf $lib liblapack.a
   else
      cd ..
   fi  
   # On efface les sources
   rm -r -f OpenBLAS*
}
install_NetLib()
{
   ##########################
   # Install de LAPACK NetLib
   ##########################
   package=lapack-$version_lapack
   if [ ! -f $package.tgz ]
   then
      # On telecharge le package si non livre
      wget_ http://www.netlib.org/lapack/$package.tgz || exit -1
   fi
   echo "Installation of $package..."
   #gunzip -c $package.tgz > $package.tar
   gunzip -f -c $package.tgz | tar -xf -
   #rm -f $package.tar
   cd $package 

   option=`$TRUST_Awk '/F77Flags/  {gsub("F77Flags =" ,"",$0);o=$0} END {print o}' $TRUST_ROOT/env/make.$TRUST_ARCH_CC"_opt"`
   [ "$TRUST_INT64" = "1" ] && option=`echo $option |sed "s/-fdefault-integer-8//g" `
   # Creation du make.inc
   echo "
   SHELL    = /bin/sh
   PLAT     = 
   FORTRAN  = $TRUST_F77
   OPTS     = $option
   DRVOPTS  = \$(OPTS)
   NOOPT    = -g -O0 -fPIC
   LOADER   = $TRUST_F77
   LOADOPTS =
   TIMER    = INT_CPU_TIME
   ARCH     = ar
   ARCHFLAGS= cr
   RANLIB   = ranlib
   BLASLIB  = ../../../libblas\$(PLAT).a
   XBLASLIB =
   LAPACKLIB= ../liblapack\$(PLAT).a
   TMGLIB   = tmglib\$(PLAT).a
   EIGSRCLIB= eigsrc\$(PLAT).a
   LINSRCLIB= linsrc\$(PLAT).a" > make.inc

   libs="blaslib lapacklib"
   $TRUST_MAKE $libs || exit -1
   cd ..
   # On efface les sources
   rm -r -f $package
   echo "Netlib Blas Netlib installed."
}
#########################
# Debut de la procedure #
#########################
if [ "$TRUST_BUILD_IN_TMP" = "1" ]
then
    name=LIBLAPACK
    build_dir=$TRUST_TMP/build/$name
    mkdir -p $build_dir
    cp -r * $build_dir
    cd $build_dir
fi

# recuperation des archives
for file in `ls $TRUST_ROOT/externalpackages/lapack/*`
do
   ln -sf $file .
done
# Nom des versions a upgrader:
version_openblas=0.3.10
# On utilise Lapack 3.1.1 si le compilateur fortran n'est pas f90 (auquel cas TRUST_USE_MUMPS=0)
version_lapack=3.4.1 && [ "$TRUST_INT64" != "1" ] && [ "$TRUST_USE_MUMPS" != 1 ] && version_lapack=3.1.1

TRY_OPENBLAS=1 # Installation d'OpenBlas (multithreade uniquement si support OpenMP active). Ecarts sur plusieurs cas fvca8 sinon
# fvca8_jdd10 ATTENTION 8 ecarts possible sur ce cas...
# fvca8_jdd11 ATTENTION 8 ecarts possible sur ce cas...
# fvca8_jdd13 ATTENTION 8 ecarts possible sur ce cas...
# fvca8_jdd5 ATTENTION 8 ecarts possible sur ce cas...
# fvca8_jdd6 ATTENTION 8 ecarts possible sur ce cas...
# fvca8_jdd9 ATTENTION 8 ecarts possible sur ce cas...
if [ "$TRY_OPENBLAS" = 1 ] && [ "$PETSC_HAVE_OPENMP" = 1 ]
then
   # Parfois OpenBlas ne s'installe pas, on switche sur la version classique
   install_OpenBlas
   [ ! -f libopenblas.a ] && install_NetLib
   # Test d'OpenBlas:
   echo "#include <cblas.h>
#include <stdio.h>

int main()
{
  int i=0;
  double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};         
  double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};  
  double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5}; 
  cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,A, 3, B, 3,2,C,3);

  for(i=0; i<9; i++)
    printf(\"%lf \", C[i]);
  printf(\"\n\");
  return 0;    
}" > test.c
   echo "Testing OpenBlas..."
   OK=0 && $TRUST_cc -o test test.c -L. -lblas -lpthread && ./test && OK=1
   [ $OK = 0 ] && install_NetLib
   echo "OpenBLAS installed." 
else
   install_NetLib
fi
mkdir -p $TRUST_LIB/src/LIBLAPACK
mv *.a $TRUST_LIB/src/LIBLAPACK
#  on efface les liens des archives
for file in `ls $TRUST_ROOT/externalpackages/lapack/*`
do
 f=`basename $file`
 [ -h $f ] && rm  $f 
done
# Nom des versions a upgrader:
exit 0
