#!/bin/bash 
cat /dev/null > nb_mailles
for f in `ls *.data`
do
	nbr_maille=`grep -i nombre_de_noeud $f | $TRUST_Awk '{print ($2-1)*($3-1)*($4-1)}'`
	if [ $nbr_maille -lt 0 ]; then nbr_maille=`echo -1*$nbr_maille | bc`; fi
	echo $f $nbr_maille >> nb_mailles
done
