#!/bin/bash 
cat /dev/null > nb_mailles
for f in `find -name "*.data"`
do
	nbr_maille=`grep -i nombre_de_noeud $f | $TRUST_Awk '{print ($2-1)*($3-1)*($4-1)}'`
	if [ $nbr_maille -lt 0 ]; then nbr_maille=`echo -1*$nbr_maille | bc`; fi
	if [ $nbr_maille -gt 1 ]; then echo $f $nbr_maille >> nb_mailles; fi
done
