#!/bin/bash 
rm -f nb_cells
for f in `find -name "*.data"`
do
  nbCells=""
  nbCells=`grep -i nombre_de_noeud $f | $TRUST_Awk '{print ($2-1)*($3-1)}'`
  [ "$nbCells" != "" ] && echo $f $nbCells >> nb_cells
done
exit 0
