#!/bin/bash

# Compare binary_QC and binary_WC simulations
compare_lata binaire_QC.lml QC_vs_WC_binaire.lml 1>verifie.log 2>&1 || exit -1

numb_diff=`awk '$1=="Number"{print $5}' verifie.log`
if [[ "$numb_diff" -gt "0" ]]
then
  echo "   ===> Error ! The simulations performed with QC and WC do not give identical results !"
  exit -1
else
  echo "   ===> All OK ! The simulations performed with QC and WC give, as expected, identical results since Pth is uniform !"
fi
