/****************************************************************************
* Copyright (c) 2024, CEA
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
* OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*****************************************************************************/

#include <Lata_2_Other.h>
#include <Lata_2_MED.h>
#include <EChaine.h>
#include <Nom.h>

Implemente_instanciable(Lata_2_MED, "Lata_To_MED|Lata_2_MED", Interprete);
// XD lata_to_med interprete lata_to_med -1 To convert results file written with LATA format to MED file. Warning: Fields located on faces are not supported yet.
// XD attr format format_lata_to_med format 1 generated file post_med.data use format (MED or LATA or LML keyword).
// XD attr file chaine file 0 LATA file to convert to the new format.
// XD attr file_med chaine file_med 0 Name of the MED file.

Sortie& Lata_2_MED::printOn(Sortie& os) const { return Interprete::printOn(os); }
Entree& Lata_2_MED::readOn(Entree& is) { return Interprete::readOn(is); }

Entree& Lata_2_MED::interpreter(Entree& is)
{
  Cerr << "Syntax Lata_To_MED::interpreter nom_lata||NOM_DU_CAS nom_fichier_sortie||NOM_DU_CAS   " << finl;
  Nom nom1, nom2;
  is >> nom1 >> nom2;

  Nom instruction("med ");
  instruction += nom1;
  instruction += " ";
  instruction += nom2;

  Cerr << "command generated by Lata_2_MED " << instruction << finl;

  Lata_2_Other l2o;
  EChaine cmd(instruction);
  l2o.interpreter(cmd);

  return is;
}
