#! /bin/bash
#
# --
# HDF5 install builder
#
# Author : Eli LAUCOIN (CEA)
# --

# defining several useful variables
TRUST_MED_HDF_SRC=`pwd`
TRUST_MED_HDF_SCRIPTS="${TRUST_MED_HDF_SRC}/scripts"

export TRUST_MED_HDF_SRC
export TRUST_MED_HDF_SCRIPTS

# loading exception functions
. "${TRUST_MED_HDF_SCRIPTS}/provided/exceptions.sh"

# loading checking functions
. "${TRUST_MED_HDF_SCRIPTS}/provided/checkers.sh"

# loading utilitary functions
. "${TRUST_MED_HDF_SCRIPTS}/provided/utils.sh"

# checking environment
check_environment

# checking HDF5's version ==> defines and exports TRUST_HDF_VERSION and TRUST_HDF_LOCATION
check_HDF_version

# checking MED's version ==> defines and exports TRUST_MED_VERSION and TRUST_MED_LOCATION
check_MED_version

# checking compatibility between HDF5's version, MED's version and user defined USE_MED_VERSION
check_versions_compatibility

# building HDF5's installer
case "x_${TRUST_HDF_LOCATION}_${TRUST_HDF_VERSION}_x" in
    "x_internal_1.8_x") install="install_HDF 1.8 internal" ;;
    "x_internal_1.6_x") install="install_HDF 1.6 internal" ;;
    "x_external_1.8_x") install="install_HDF 1.8 external" ;;
    "x_external_1.6_x") install="install_HDF 1.6 external" ;;
    *) raise_invalid_HDF_configuration_exception "${TRUST_HDF_VERSION}" "${TRUST_HDF_LOCATION}" ;;
esac

header="# generated by ${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF_builder.sh"
input="${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh.in"
output="${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh"

cp "${input}" "${output}"

sed_ "${output}" "s?%install%?${install}?g"
sed_ "${output}" "s?%header%?${header}?g"
sed_ "${output}" "s?template??g" 

# updating HDF5's installer
test ! -d ${TRUST_MED_HDF_SCRIPTS}/generated && mkdir ${TRUST_MED_HDF_SCRIPTS}/generated

if test -f "${TRUST_MED_HDF_SCRIPTS}/generated/install_HDF.sh" 
then
    diff "${TRUST_MED_HDF_SCRIPTS}/generated/install_HDF.sh" "${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh" 1>/dev/null 2>&1
    if test "$?" != "0"
    then
	rm -f "${TRUST_MED_HDF_SCRIPTS}/generated/install_HDF.sh"
	mv "${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh" "${TRUST_MED_HDF_SCRIPTS}/generated/install_HDF.sh"
    else
	rm -f "${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh"
    fi
else
    mv "${TRUST_MED_HDF_SCRIPTS}/provided/install_HDF.sh" "${TRUST_MED_HDF_SCRIPTS}/generated/install_HDF.sh"
fi
