#!/bin/bash

tot=`grep "Temps total" $1.TU | awk '{printf("%f ", $NF)}' | awk '{print ($1+$2)}'`
nu=`awk '/Order of the PETSc matrix/ {N=$7} END {print N}' $1.out`
resp=`tail -1 $1_ERRP.son | awk '{print $2}'`
resv=`tail -1 $1_ERRV.son | awk '{print $2}'`
echo $nu $resp $tot > conv_p
echo $nu $resv $tot > conv_v
