#!/bin/bash
# permet de tester la dependance a la rotation du Keps 2D VEF
modif_lml()
{
org_lml=$1
res_lml=$2

ligne=`grep -n TOPOLOGIE $org_lml | $TRUST_Awk -F: '{print $1}' `
sed "$ligne,$ d" $res_lml > modif.lml
echo TOPOLOGIE >> modif.lml
sed "1,$ligne d" $org_lml >>modif.lml
echo $org_lml $res_lml ecarts:
compare_lata modif.lml $res_lml || exit -1
}

triou Marche 
triou Marche_y  
triou Marche_incline 
modif_lml Marche.lml Marche_y.lml
modif_lml Marche.lml Marche_incline.lml
